(() => {
"use strict";
const $=id=>document.getElementById(id), canvas=$("tahoeCanvas"), ctx=canvas.getContext("2d");
const W=canvas.width,H=canvas.height,WORLD=4600,FLOOR=570,SAVE="3dudes1quest_tahoe_v211";
const ui={opening:$("openingCard"),begin:$("beginTahoe"),mission:$("missionCard"),tip:$("playTip"),input:$("inputStatus"),pause:$("pauseMenu"),pauseBtn:$("pauseBtn"),resume:$("resumeTahoe"),restart:$("restartTahoe"),replay:$("replayTahoe"),switch:$("switchBtn"),power:$("powerBtn"),trail:$("trailProgressFill"),health:$("hudHealth"),beetles:$("hudBeetles"),memories:$("hudMemories"),altitude:$("hudAltitude"),dude:$("hudDude"),portrait:$("hudPortrait"),objectiveTitle:$("objectiveTitle"),objectiveText:$("objectiveText"),memory:$("memoryCard"),memoryTitle:$("memoryCardTitle"),memoryText:$("memoryCardText"),checkpoint:$("checkpointCard"),finale:$("finaleBanner"),trailhead:$("trailheadCard"),continuePortal:$("continueToPortal"),cinematic:$("cinematicCaption"),dialogue:$("dialogue")};
const dudes=[["Will","W","will"],["Daniel","D","daniel"],["Caleb","C","caleb"]];
const imgs={}; for(const k of ["will","daniel","caleb","rigsby"]){const i=new Image();i.src=`assets/sprites_hd/${k}_walk.png`;imgs[k]=i;}
const state={started:false,paused:false,complete:false,finale:false,portal:false,keys:{left:false,right:false,jump:false,power:false},player:{x:250,y:FLOOR-102,w:72,h:102,vx:0,vy:0,on:true,face:1,frame:0},rigsby:{x:140,y:FLOOR-58,w:88,h:58,frame:0},zoey:{x:70,y:FLOOR-48,w:68,h:46},camera:0,dude:0,health:5,defeated:0,mem:[false,false,false,false],checkpoint:250,inv:0,cool:0,blasts:[],particles:[],trail:[],time:0,beetles:[
{x:1450,v:1.3,min:1360,max:1570,alive:true},{x:2020,v:-1.4,min:1900,max:2180,alive:true},{x:2720,v:1.5,min:2590,max:2860,alive:true},{x:3370,v:-1.6,min:3240,max:3500,alive:true},{x:3970,v:1.8,min:3850,max:4110,alive:true}],
discoveries:[{x:820,t:"SUNRISE AT THE LAKE",d:"The water like glass before the world wakes."},{x:2140,t:"RIGSBY'S TAHOE DAYS",d:"Cold paws, brave swimming, pure beagle joy."},{x:3200,t:"TAHOE IN WINTER",d:"Snow on every branch and frozen mountain air."},{x:4010,t:"THE OVERLOOK",d:"Sixteen years here and still something new."}]};
function ground(x){return x<1050?FLOOR:FLOOR-Math.min(95,(x-1050)*.024)}
function overlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function objective(a,b){ui.objectiveTitle.textContent=a;ui.objectiveText.textContent=b}
function inputLabel(t){ui.input.querySelector("b").textContent=t;ui.input.classList.add("active");clearTimeout(inputLabel.t);inputLabel.t=setTimeout(()=>{ui.input.classList.remove("active");ui.input.querySelector("b").textContent="READY"},500)}
function setDude(n){state.dude=(n+3)%3;ui.dude.textContent=dudes[state.dude][0];ui.portrait.textContent=dudes[state.dude][1]}
function save(){try{localStorage.setItem(SAVE,JSON.stringify({checkpoint:state.checkpoint,defeated:state.defeated,alive:state.beetles.map(b=>b.alive),mem:state.mem,dude:state.dude}))}catch(e){}}
function load(){try{const d=JSON.parse(localStorage.getItem(SAVE)||"null");if(!d)return;state.checkpoint=Number(d.checkpoint)||250;state.defeated=Math.min(5,Number(d.defeated)||0);if(Array.isArray(d.alive))state.beetles.forEach((b,i)=>b.alive=d.alive[i]!==false);if(Array.isArray(d.mem))state.mem=d.mem.slice(0,4).map(Boolean);setDude(Number(d.dude)||0);state.player.x=state.checkpoint;state.player.y=ground(state.player.x)-state.player.h;ui.beetles.textContent=state.defeated;ui.memories.textContent=state.mem.filter(Boolean).length}catch(e){}}
function reset(clear=false){if(clear)try{localStorage.removeItem(SAVE)}catch(e){};Object.assign(state.player,{x:250,y:FLOOR-102,vx:0,vy:0,on:true,face:1,frame:0});state.camera=0;state.started=true;state.paused=false;state.complete=false;state.finale=false;state.portal=false;state.health=5;state.defeated=0;state.mem=[false,false,false,false];state.checkpoint=250;state.blasts=[];state.particles=[];state.trail=[];state.beetles.forEach(b=>b.alive=true);setDude(0);if(!clear)load();ui.health.textContent=state.health;ui.beetles.textContent=state.defeated;ui.memories.textContent=state.mem.filter(Boolean).length;ui.opening.classList.add("hidden");ui.pause.classList.add("hidden");ui.trailhead.classList.add("hidden");ui.finale.classList.add("hidden");ui.dialogue.classList.add("hidden");ui.cinematic.classList.add("hidden");ui.mission.classList.remove("hidden");setTimeout(()=>ui.mission.classList.add("hidden"),2200);ui.tip.classList.remove("hidden");setTimeout(()=>ui.tip.classList.add("hidden"),4500);objective("Clear five Pine Beetles","Move right. Jump or use Power to defeat them.");canvas.focus({preventScroll:true})}
function press(a,v){if(a==="power"&&v&&!state.keys.power)blast();if(a==="jump"&&v&&!state.keys.jump)jump();state.keys[a]=v}
function jump(){if(!state.started||state.paused||state.complete)return;if(state.player.on){state.player.vy=-13.2;state.player.on=false;inputLabel("JUMP")}}
function blast(){if(!state.started||state.paused||state.complete||state.cool>0)return;state.cool=420;state.blasts.push({x:state.player.x+state.player.w/2+state.player.face*30,y:state.player.y+48,v:state.player.face*12,life:80});inputLabel("POWER")}
function defeat(b){if(!b.alive)return;b.alive=false;state.defeated++;ui.beetles.textContent=state.defeated;state.player.vy=-8;for(let i=0;i<18;i++)state.particles.push({x:b.x,y:ground(b.x)-20,vx:(Math.random()-.5)*6,vy:-Math.random()*5,life:40});objective(state.defeated<5?"Keep clearing beetles":"Reach the summit",state.defeated<5?`${5-state.defeated} remaining.`:"The trailhead is open.");save()}
function collect(i){if(state.mem[i])return;state.mem[i]=true;ui.memories.textContent=state.mem.filter(Boolean).length;ui.memoryTitle.textContent=state.discoveries[i].t;ui.memoryText.textContent=state.discoveries[i].d;ui.memory.classList.remove("hidden");setTimeout(()=>ui.memory.classList.add("hidden"),2400);save()}
function finish(){if(state.finale)return;state.finale=true;state.portal=true;ui.finale.classList.remove("hidden");objective("Enter the Alaska Portal","Walk into the glowing portal at the summit.");setTimeout(()=>ui.finale.classList.add("hidden"),2800)}
function update(dt){if(!state.started||state.paused||state.complete)return;state.time+=dt;const p=state.player;const dir=state.keys.left?-1:state.keys.right?1:0;p.vx+=(dir*6-p.vx)*.18;if(!dir)p.vx*=.82;p.x=Math.max(0,Math.min(WORLD-80,p.x+p.vx));if(dir)p.face=dir;p.vy+=.68;p.y+=p.vy;const g=ground(p.x);if(p.y+p.h>=g){p.y=g-p.h;p.vy=0;p.on=true}else p.on=false;p.frame+=Math.abs(p.vx)*.06;state.cool=Math.max(0,state.cool-dt);
for(const b of state.beetles){if(!b.alive)continue;b.x+=b.v;if(b.x<b.min||b.x>b.max)b.v*=-1;const box={x:b.x-23,y:ground(b.x)-30,w:46,h:30};if(overlap(p,box)){if(p.vy>0&&p.y+p.h<box.y+25)defeat(b);else if(state.inv<=0){state.health--;ui.health.textContent=state.health;state.inv=1000;p.vy=-8;p.vx=p.x<b.x?-7:7;if(state.health<=0){state.health=5;ui.health.textContent=5;p.x=state.checkpoint;p.y=ground(p.x)-p.h}}}}
state.inv=Math.max(0,state.inv-dt);
for(const s of state.blasts){s.x+=s.v;s.life--;for(const b of state.beetles){if(!b.alive)continue;const box={x:b.x-23,y:ground(b.x)-30,w:46,h:30};if(overlap({x:s.x-25,y:s.y-20,w:50,h:40},box)){defeat(b);s.life=0}}}state.blasts=state.blasts.filter(s=>s.life>0&&s.x>0&&s.x<WORLD);
state.discoveries.forEach((m,i)=>{if(!state.mem[i]&&Math.abs(p.x-m.x)<42)collect(i)});
if(p.x>2850&&state.checkpoint<2800){state.checkpoint=2860;ui.checkpoint.classList.remove("hidden");setTimeout(()=>ui.checkpoint.classList.add("hidden"),1800);save()}
if(p.x>4300&&!state.portal){if(state.defeated>=5)finish();else{p.x=4250;objective("The trail is blocked",`Defeat ${5-state.defeated} more beetle${5-state.defeated===4?"":"s"}.`)}}
if(state.portal&&p.x>4360){state.complete=true;save();document.body.classList.add("portalExit");setTimeout(()=>location.href="alaska.html",700)}
state.trail.push({x:p.x,y:p.y});if(state.trail.length>60)state.trail.shift();const r=state.trail[Math.max(0,state.trail.length-18)]||{x:p.x-100,y:p.y};const z=state.trail[Math.max(0,state.trail.length-36)]||{x:p.x-165,y:p.y};state.rigsby.x+=(r.x-state.rigsby.x)*.12;state.rigsby.y+=(ground(state.rigsby.x)-state.rigsby.h-state.rigsby.y)*.22;state.rigsby.frame+=Math.abs(state.rigsby.x-r.x)*.03;state.zoey.x+=(z.x-state.zoey.x)*.09;state.zoey.y+=(ground(state.zoey.x)-state.zoey.h-state.zoey.y)*.2;
state.camera+=(Math.max(0,Math.min(WORLD-W,p.x-W*.34))-state.camera)*.09;ui.trail.style.width=Math.min(100,p.x/(WORLD-300)*100)+"%";ui.altitude.textContent=p.x<1100?"Emerald Shore":p.x<2360?"Whispering Pines":p.x<3200?"Eagle Creek":p.x<4110?"Granite Crown":"Infested Trailhead";
for(const q of state.particles){q.x+=q.vx;q.y+=q.vy;q.vy+=.15;q.life--}state.particles=state.particles.filter(q=>q.life>0)}
function sprite(img,x,y,w,h,frame,face=1){if(!img.complete||!img.naturalWidth){ctx.fillStyle="#ff58ae";ctx.fillRect(x,y,w,h);return}const sw=img.naturalWidth/8;ctx.save();if(face<0){ctx.translate(x+w,y);ctx.scale(-1,1);ctx.drawImage(img,(frame|0)%8*sw,0,sw,img.naturalHeight,0,0,w,h)}else ctx.drawImage(img,(frame|0)%8*sw,0,sw,img.naturalHeight,x,y,w,h);ctx.restore()}
function draw(){ctx.clearRect(0,0,W,H);let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,"#82d2eb");g.addColorStop(.55,"#c7eced");g.addColorStop(1,"#3e8c76");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle="#4b7180";for(let i=0;i<8;i++){const x=i*230-state.camera*.12;ctx.beginPath();ctx.moveTo(x,390);ctx.lineTo(x+120,180+(i%3)*55);ctx.lineTo(x+260,390);ctx.fill()}ctx.fillStyle="#2eaccb";ctx.fillRect(0,365,W,205);ctx.fillStyle="#d4be87";ctx.beginPath();ctx.moveTo(-state.camera,FLOOR);ctx.lineTo(WORLD-state.camera,FLOOR-95);ctx.lineTo(WORLD-state.camera,H);ctx.lineTo(-state.camera,H);ctx.fill();ctx.fillStyle="#3f704b";for(let i=0;i<55;i++){const wx=900+i*78,x=wx-state.camera,y=ground(wx);ctx.beginPath();ctx.moveTo(x,y-150);ctx.lineTo(x-42,y);ctx.lineTo(x+42,y);ctx.fill()}
for(const m of state.discoveries){const i=state.discoveries.indexOf(m);if(state.mem[i])continue;const x=m.x-state.camera,y=ground(m.x)-62;ctx.fillStyle="#ffe783";ctx.beginPath();ctx.arc(x,y,18+Math.sin(state.time*.006+i)*3,0,Math.PI*2);ctx.fill();ctx.font="20px serif";ctx.textAlign="center";ctx.fillText("📸",x,y+7)}
for(const b of state.beetles){if(!b.alive)continue;const x=b.x-state.camera,y=ground(b.x)-18;ctx.fillStyle="#5d241b";ctx.beginPath();ctx.ellipse(x,y,23,15,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#1e1110";ctx.beginPath();ctx.arc(x-20,y,8,0,Math.PI*2);ctx.fill()}
for(const s of state.blasts){const x=s.x-state.camera;ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(x,s.y,20,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#ff5ab7";ctx.lineWidth=8;ctx.stroke()}
for(const q of state.particles){ctx.globalAlpha=Math.max(0,q.life/40);ctx.fillStyle="#ffe57f";ctx.fillRect(q.x-state.camera,q.y,4,4)}ctx.globalAlpha=1;
const zx=state.zoey.x-state.camera,zy=state.zoey.y;ctx.save();ctx.translate(zx,zy);ctx.fillStyle="#f4efe5";ctx.beginPath();ctx.ellipse(34,25,29,17,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#7b4b31";ctx.beginPath();ctx.ellipse(55,16,15,13,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#5a3425";ctx.beginPath();ctx.ellipse(48,8,7,14,-.5,0,Math.PI*2);ctx.ellipse(61,8,7,14,.5,0,Math.PI*2);ctx.fill();ctx.fillStyle="#111";ctx.beginPath();ctx.arc(61,15,2,0,Math.PI*2);ctx.fill();ctx.restore();
sprite(imgs.rigsby,state.rigsby.x-state.camera,state.rigsby.y,state.rigsby.w,state.rigsby.h,state.rigsby.frame,state.player.face);if(!(state.inv>0&&Math.floor(state.inv/90)%2===0))sprite(imgs[dudes[state.dude][2]],state.player.x-state.camera,state.player.y,state.player.w,state.player.h,state.player.frame,state.player.face);
if(state.portal){const x=4380-state.camera,y=360,p=1+Math.sin(state.time*.008)*.08;ctx.save();ctx.translate(x,y);ctx.scale(p,p);ctx.strokeStyle="#ff58ba";ctx.lineWidth=16;ctx.beginPath();ctx.ellipse(0,0,58,82,0,0,Math.PI*2);ctx.stroke();ctx.strokeStyle="#5de4df";ctx.lineWidth=9;ctx.beginPath();ctx.ellipse(0,0,40,62,0,0,Math.PI*2);ctx.stroke();ctx.restore();ctx.fillStyle="#fff";ctx.font="900 16px system-ui";ctx.textAlign="center";ctx.fillText("ALASKA",x,y-105)}
if(!state.started){ctx.fillStyle="rgba(2,15,28,.25)";ctx.fillRect(0,0,W,H)}}
function release(){for(const k in state.keys)state.keys[k]=false}
document.querySelectorAll("[data-action]").forEach(b=>{const a=b.dataset.action;b.addEventListener("pointerdown",e=>{e.preventDefault();if(!state.started||state.paused)return;press(a,true);b.classList.add("isPressed")},{passive:false});const up=e=>{e.preventDefault();press(a,false);b.classList.remove("isPressed")};b.addEventListener("pointerup",up,{passive:false});b.addEventListener("pointercancel",up,{passive:false})});
addEventListener("keydown",e=>{let a=e.code==="ArrowLeft"||e.code==="KeyA"?"left":e.code==="ArrowRight"||e.code==="KeyD"?"right":e.code==="ArrowUp"||e.code==="KeyW"||e.code==="Space"?"jump":e.code==="KeyX"||e.code==="KeyF"?"power":"";if(a){e.preventDefault();press(a,true)}});addEventListener("keyup",e=>{let a=e.code==="ArrowLeft"||e.code==="KeyA"?"left":e.code==="ArrowRight"||e.code==="KeyD"?"right":e.code==="ArrowUp"||e.code==="KeyW"||e.code==="Space"?"jump":e.code==="KeyX"||e.code==="KeyF"?"power":"";if(a){e.preventDefault();press(a,false)}});addEventListener("blur",release);
ui.begin.addEventListener("click",()=>reset(false));ui.switch.addEventListener("click",()=>setDude(state.dude+1));ui.pauseBtn.addEventListener("click",()=>{if(!state.started)return;state.paused=!state.paused;ui.pause.classList.toggle("hidden",!state.paused)});ui.resume.addEventListener("click",()=>{state.paused=false;ui.pause.classList.add("hidden")});ui.restart.addEventListener("click",()=>reset(true));ui.replay.addEventListener("click",()=>reset(true));ui.continuePortal.addEventListener("click",()=>{state.portal=true;state.player.x=4200;state.player.y=ground(4200)-state.player.h;ui.trailhead.classList.add("hidden")});
let last=performance.now();function loop(now){const dt=Math.min(32,now-last);last=now;try{update(dt);draw()}catch(err){console.error("Tahoe 2.1.1 recovered:",err);objective("Tahoe recovered","Press Restart Tahoe if controls stop.");}requestAnimationFrame(loop)}requestAnimationFrame(loop);
window.__TAHOE_RELEASE__={version:"2.1.1",name:"Playable Fix",features:["safe Play flow","movement","jump","power","five beetles","four memories","Rigsby and Zoey distinct","Alaska exit"]};
})();