(() => {
"use strict";
const $=id=>document.getElementById(id), canvas=$("tahoeCanvas"), ctx=canvas.getContext("2d");
const W=canvas.width,H=canvas.height,WORLD=9200,FLOOR=570,SAVE="3dudes1quest_tahoe_v230",RELEASE="2.3.0";
const platforms=[
{x:1320,y:438,w:190,h:18,kind:"log"},{x:1580,y:385,w:170,h:18,kind:"rock"},{x:1840,y:330,w:190,h:18,kind:"rock"},
{x:2800,y:410,w:180,h:18,kind:"log"},{x:3060,y:350,w:170,h:18,kind:"rock"},{x:3320,y:292,w:210,h:18,kind:"rock"},
{x:4100,y:420,w:220,h:18,kind:"bridge"},{x:4350,y:420,w:220,h:18,kind:"bridge"},{x:4600,y:420,w:220,h:18,kind:"bridge"},
{x:5480,y:385,w:180,h:18,kind:"rock"},{x:5740,y:325,w:170,h:18,kind:"rock"},{x:6000,y:265,w:210,h:18,kind:"rock"},
{x:7050,y:400,w:190,h:18,kind:"log"},{x:7330,y:335,w:180,h:18,kind:"rock"},{x:7610,y:270,w:210,h:18,kind:"lookout"}
];
const zoneMilestones=[{x:1050,t:"Whispering Pines",m:"Climb above Emerald Shore."},{x:2600,t:"Eagle Creek",m:"Cross the waterfall ledges."},{x:4050,t:"Fallen Timber Crossing",m:"Fight across the broken log bridge."},{x:5300,t:"Crystal Cave",m:"Take the high path through the hidden cave."},{x:6850,t:"Granite Crown",m:"Climb to Tahoe's highest overlook."},{x:8200,t:"Infested Summit",m:"Clear the final beetle colony."}];
const ui={opening:$("openingCard"),begin:$("beginTahoe"),mission:$("missionCard"),tip:$("playTip"),input:$("inputStatus"),pause:$("pauseMenu"),pauseBtn:$("pauseBtn"),resume:$("resumeTahoe"),restart:$("restartTahoe"),replay:$("replayTahoe"),switch:$("switchBtn"),power:$("powerBtn"),trail:$("trailProgressFill"),health:$("hudHealth"),beetles:$("hudBeetles"),memories:$("hudMemories"),altitude:$("hudAltitude"),dude:$("hudDude"),portrait:$("hudPortrait"),objectiveTitle:$("objectiveTitle"),objectiveText:$("objectiveText"),memory:$("memoryCard"),memoryTitle:$("memoryCardTitle"),memoryText:$("memoryCardText"),checkpoint:$("checkpointCard"),finale:$("finaleBanner"),trailhead:$("trailheadCard"),continuePortal:$("continueToPortal"),cinematic:$("cinematicCaption"),dialogue:$("dialogue"),combo:$("comboHud"),score:$("hudScore"),powerFill:$("powerChargeFill"),powerLabel:$("powerChargeLabel")};
const dudes=[{name:"Will",letter:"W",key:"will",speed:6.4,jump:13.8,power:1.18},{name:"Daniel",letter:"D",key:"daniel",speed:7.2,jump:13.4,power:1},{name:"Caleb",letter:"C",key:"caleb",speed:6.1,jump:14.8,power:1.05}];
const imgs={}; for(const k of ["will","daniel","caleb","rigsby"]){const i=new Image();i.src=`assets/sprites_hd/${k}_walk.png`;imgs[k]=i;}
const makeBeetle=(x,type="walker",min=x-120,max=x+120)=>({x,y:0,w:type==="armored"?58:48,h:type==="flyer"?34:30,v:type==="charger"?1.2:1.45,min,max,alive:true,type,hp:type==="armored"?2:1,flash:0,stun:0,alert:0,phase:Math.random()*6.28});
const state={started:false,paused:false,complete:false,finale:false,portal:false,keys:{left:false,right:false,jump:false,power:false},player:{x:250,y:FLOOR-102,w:72,h:102,vx:0,vy:0,on:true,face:1,frame:0},rigsby:{x:140,y:FLOOR-58,w:88,h:58,frame:0},zoey:{x:70,y:FLOOR-48,w:68,h:46},camera:0,dude:0,health:5,maxHealth:5,defeated:0,totalBeetles:18,mem:[false,false,false,false,false,false],checkpoint:250,lastZone:-1,inv:0,blasts:[],particles:[],floaters:[],drops:[],trail:[],crystals:[{x:1700,y:290,got:false},{x:3180,y:310,got:false},{x:4490,y:365,got:false},{x:5940,y:220,got:false},{x:7480,y:290,got:false}],time:0,coyote:0,jumpBuffer:0,powerCharging:false,powerCharge:0,powerCooldown:0,combo:0,comboTimer:0,score:0,shake:0,flash:0,hitStop:0,beetles:[
makeBeetle(1180),makeBeetle(1480,"charger"),makeBeetle(1780,"flyer"),makeBeetle(2180,"walker"),
makeBeetle(2670,"armored"),makeBeetle(3020,"charger"),makeBeetle(3420,"flyer"),makeBeetle(3820,"walker"),
makeBeetle(4250,"charger"),makeBeetle(4680,"armored"),makeBeetle(5120,"flyer"),makeBeetle(5560,"walker"),
makeBeetle(6120,"armored"),makeBeetle(6580,"charger"),makeBeetle(7110,"flyer"),makeBeetle(7620,"walker"),
makeBeetle(8240,"charger"),makeBeetle(8660,"armored")],discoveries:[
{x:900,t:"SUNRISE AT THE LAKE",d:"The water like glass before the world wakes."},
{x:2450,t:"RIGSBY'S TAHOE DAYS",d:"Cold paws, brave swimming, pure beagle joy."},
{x:3900,t:"THE FALLEN TIMBER",d:"Every storm leaves a new path forward."},
{x:5350,t:"CRYSTAL CAVE",d:"Tahoe keeps entire worlds hidden beneath the granite."},
{x:6900,t:"TAHOE IN WINTER",d:"Snow on every branch and frozen mountain air."},
{x:8050,t:"THE OVERLOOK",d:"Sixteen years here and still something new."}]};
function ground(x){
if(x<1000)return FLOOR;
if(x<2400)return 560-Math.min(75,(x-1000)*.045)+Math.sin(x/170)*8;
if(x<3900)return 500-Math.sin((x-2400)/190)*24;
if(x<5000)return 525+Math.sin((x-3900)/155)*18;
if(x<6500)return 505-Math.min(95,(x-5000)*.05)+Math.sin(x/160)*10;
if(x<8100)return 440-Math.sin((x-6500)/175)*22;
return 430-Math.min(55,(x-8100)*.045)+Math.sin(x/130)*7
}
function overlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function objective(a,b){ui.objectiveTitle.textContent=a;ui.objectiveText.textContent=b}
function inputLabel(t){if(!ui.input)return;ui.input.querySelector("b").textContent=t;ui.input.classList.add("active");clearTimeout(inputLabel.t);inputLabel.t=setTimeout(()=>{ui.input.classList.remove("active");ui.input.querySelector("b").textContent="READY"},600)}
function setDude(n){state.dude=(n+3)%3;const d=dudes[state.dude];ui.dude.textContent=d.name;ui.portrait.textContent=d.letter;inputLabel(`${d.name.toUpperCase()} READY`)}
function addParticles(x,y,count,kind="rainbow",power=1){for(let i=0;i<count;i++)state.particles.push({x,y,vx:(Math.random()-.5)*7*power,vy:(Math.random()-.8)*7*power,life:28+Math.random()*38,size:2+Math.random()*5,kind,rot:Math.random()*6.28})}
function floater(text,x,y,kind="score"){state.floaters.push({text,x,y,life:70,kind})}
function setShake(n){state.shake=Math.max(state.shake,n)}
function save(){try{localStorage.setItem(SAVE,JSON.stringify({checkpoint:state.checkpoint,defeated:state.defeated,alive:state.beetles.map(b=>b.alive),hp:state.beetles.map(b=>b.hp),mem:state.mem,dude:state.dude,score:state.score,maxHealth:state.maxHealth}))}catch(_) {}}
function load(){try{const d=JSON.parse(localStorage.getItem(SAVE)||"null");if(!d)return;state.checkpoint=Number(d.checkpoint)||250;state.defeated=Math.min(state.totalBeetles,Number(d.defeated)||0);if(Array.isArray(d.alive))state.beetles.forEach((b,i)=>b.alive=d.alive[i]!==false);if(Array.isArray(d.hp))state.beetles.forEach((b,i)=>b.hp=Number(d.hp[i])||b.hp);if(Array.isArray(d.mem))state.mem=d.mem.slice(0,6).map(Boolean);state.score=Number(d.score)||0;state.maxHealth=Math.max(5,Number(d.maxHealth)||5);setDude(Number(d.dude)||0);state.player.x=state.checkpoint;state.player.y=ground(state.player.x)-state.player.h;syncHud()}catch(_) {}}
function syncHud(){ui.health.textContent=`${state.health}/${state.maxHealth}`;ui.beetles.textContent=state.defeated;ui.memories.textContent=state.mem.filter(Boolean).length;ui.score.textContent=state.score.toLocaleString();ui.combo.textContent=state.combo>1?`${state.combo}x COMBO`:"";ui.combo.classList.toggle("show",state.combo>1)}
function reset(clear=false){if(clear)try{localStorage.removeItem(SAVE)}catch(_){};Object.assign(state.player,{x:250,y:FLOOR-102,vx:0,vy:0,on:true,face:1,frame:0});Object.assign(state,{camera:0,started:true,paused:false,complete:false,finale:false,portal:false,health:state.maxHealth,defeated:0,mem:[false,false,false,false,false,false],checkpoint:250,lastZone:-1,blasts:[],particles:[],floaters:[],drops:[],trail:[],crystals:[{x:1700,y:290,got:false},{x:3180,y:310,got:false},{x:4490,y:365,got:false},{x:5940,y:220,got:false},{x:7480,y:290,got:false}],combo:0,comboTimer:0,score:0,powerCharging:false,powerCharge:0,powerCooldown:0,shake:0,flash:0,hitStop:0});state.beetles=[makeBeetle(1180),makeBeetle(1480,"charger"),makeBeetle(1780,"flyer"),makeBeetle(2180),makeBeetle(2670,"armored"),makeBeetle(3020,"charger"),makeBeetle(3420,"flyer"),makeBeetle(3820),makeBeetle(4250,"charger"),makeBeetle(4680,"armored"),makeBeetle(5120,"flyer"),makeBeetle(5560),makeBeetle(6120,"armored"),makeBeetle(6580,"charger"),makeBeetle(7110,"flyer"),makeBeetle(7620),makeBeetle(8240,"charger"),makeBeetle(8660,"armored")];setDude(0);if(!clear)load();ui.opening.classList.add("hidden");ui.pause.classList.add("hidden");ui.trailhead.classList.add("hidden");ui.finale.classList.add("hidden");ui.dialogue.classList.add("hidden");ui.cinematic.classList.add("hidden");ui.mission.classList.remove("hidden");setTimeout(()=>ui.mission.classList.add("hidden"),2400);ui.tip.classList.remove("hidden");setTimeout(()=>ui.tip.classList.add("hidden"),6000);objective("Explore the expanded Tahoe trail","Climb ledges, cross the log bridge, find the cave, and clear every beetle.");syncHud();canvas.focus({preventScroll:true})}
function press(a,v){if(a==="power"){if(v&&!state.keys.power)startCharge();if(!v&&state.keys.power)releaseCharge()}if(a==="jump"&&v&&!state.keys.jump){state.jumpBuffer=155;tryJump()}state.keys[a]=v}
function tryJump(){if(!state.started||state.paused||state.complete)return;if(state.player.on||state.coyote>0){state.player.vy=-dudes[state.dude].jump;state.player.on=false;state.coyote=0;state.jumpBuffer=0;addParticles(state.player.x+36,state.player.y+100,8,"dust",.55);inputLabel("JUMP")}}
function startCharge(){if(!state.started||state.paused||state.complete||state.powerCooldown>0)return;state.powerCharging=true;state.powerCharge=0;ui.power.classList.add("charging");inputLabel("CHARGING")}
function releaseCharge(){if(!state.powerCharging)return;const charge=Math.max(.12,Math.min(1,state.powerCharge));state.powerCharging=false;ui.power.classList.remove("charging");state.powerCooldown=260+charge*360;const d=dudes[state.dude],p=state.player;state.blasts.push({x:p.x+p.w/2+p.face*35,y:p.y+46,v:p.face*(12+charge*5),life:55+charge*42,charge:charge*d.power,pierce:charge>.62?Math.ceil(charge*5):1,hits:0});addParticles(p.x+p.w/2,p.y+48,14+Math.floor(charge*28),"rainbow",.8+charge);setShake(3+charge*8);state.flash=Math.max(state.flash,charge*.45);inputLabel(charge>.84?"SUPERMAN BLAST!":charge>.45?"POWER BLAST!":"RAINBOW BLAST!")}
function comboHit(x,y,base=100){state.combo=state.comboTimer>0?state.combo+1:1;state.comboTimer=1800;const points=base*state.combo;state.score+=points;floater(state.combo>1?`${state.combo}x +${points}`:`+${points}`,x,y,"combo");syncHud()}
function damageBeetle(b,mode,power=1){if(!b.alive||b.stun>0)return false;if(b.type==="armored"&&mode==="stomp"){b.flash=180;b.stun=350;floater("ARMORED!",b.x,b.y-30,"warning");setShake(4);state.player.vy=-10;return false}b.hp-=power;b.flash=160;b.stun=140;if(b.hp>0){floater("CRACK!",b.x,b.y-28,"warning");setShake(5);return false}defeat(b,mode);return true}
function defeat(b,mode){if(!b.alive)return;b.alive=false;state.defeated++;comboHit(b.x,b.y-20,mode==="stomp"?130:100);addParticles(b.x,b.y,28,"leaves",1.1);addParticles(b.x,b.y,18,"rainbow",.9);setShake(mode==="stomp"?8:6);state.hitStop=mode==="stomp"?65:40;if(mode==="stomp")state.player.vy=-11.5;if(Math.random()<.28)state.drops.push({x:b.x,y:b.y-20,vx:(Math.random()-.5)*2,vy:-5,type:Math.random()<.42?"heart":"crystal",life:900});objective(state.defeated<state.totalBeetles?"Keep clearing beetles":"Reach the summit",state.defeated<state.totalBeetles?`${state.totalBeetles-state.defeated} beetles remaining.`:"The summit portal is awakening.");syncHud();save()}
function hurt(sourceX){if(state.inv>0||state.complete)return;state.health--;state.inv=1100;state.combo=0;state.comboTimer=0;state.player.vy=-8.5;state.player.vx=state.player.x<sourceX?-8:8;state.flash=.48;setShake(10);addParticles(state.player.x+36,state.player.y+48,18,"damage",1);if(state.health<=0){state.health=state.maxHealth;state.player.x=state.checkpoint;state.player.y=ground(state.player.x)-state.player.h;state.player.vx=state.player.vy=0;objective("Back at the checkpoint","Keep fighting. Your progress is safe.")}syncHud()}
function collect(i){if(state.mem[i])return;state.mem[i]=true;state.score+=500;ui.memoryTitle.textContent=state.discoveries[i].t;ui.memoryText.textContent=state.discoveries[i].d;ui.memory.classList.remove("hidden");setTimeout(()=>ui.memory.classList.add("hidden"),2600);addParticles(state.discoveries[i].x,ground(state.discoveries[i].x)-60,38,"rainbow",1);floater("MEMORY +500",state.discoveries[i].x,ground(state.discoveries[i].x)-90,"combo");syncHud();save()}
function finish(){if(state.finale)return;state.finale=true;state.portal=true;ui.finale.classList.remove("hidden");objective("Enter the Alaska Portal","Walk into the glowing portal at the summit.");setTimeout(()=>ui.finale.classList.add("hidden"),3200)}
function updateBeetle(b,dt){if(!b.alive)return;b.flash=Math.max(0,b.flash-dt);b.stun=Math.max(0,b.stun-dt);if(b.stun>0)return;const p=state.player,dist=p.x-b.x;b.alert=Math.abs(dist)<330?Math.min(1,b.alert+dt*.004):Math.max(0,b.alert-dt*.0015);if(b.type==="flyer"){b.x+=b.v*(1+b.alert*.5);if(b.x<b.min||b.x>b.max)b.v*=-1;b.y=ground(b.x)-125+Math.sin(state.time*.006+b.phase)*42}else{const chase=b.alert>0.55?Math.sign(dist):Math.sign(b.v);let speed=Math.abs(b.v);if(b.type==="charger"&&b.alert>.72)speed=4.4;b.x+=chase*speed;if(b.x<b.min||b.x>b.max){b.x=Math.max(b.min,Math.min(b.max,b.x));b.v*=-1}b.y=ground(b.x)-b.h}}
function update(dt){if(!state.started||state.paused||state.complete)return;if(state.hitStop>0){state.hitStop-=dt;return}state.time+=dt;const p=state.player,d=dudes[state.dude],oldBottom=p.y+p.h;state.coyote=p.on?125:Math.max(0,state.coyote-dt);state.jumpBuffer=Math.max(0,state.jumpBuffer-dt);state.comboTimer=Math.max(0,state.comboTimer-dt);if(state.comboTimer===0&&state.combo){state.combo=0;syncHud()}if(state.powerCharging){state.powerCharge=Math.min(1,state.powerCharge+dt/1500);ui.powerFill.style.width=`${state.powerCharge*100}%`;ui.powerLabel.textContent=state.powerCharge>.84?"SUPERMAN":state.powerCharge>.45?"POWER":"CHARGE"}else{ui.powerFill.style.width="0%";ui.powerLabel.textContent=state.powerCooldown>0?"COOLING":"READY"}state.powerCooldown=Math.max(0,state.powerCooldown-dt);ui.power.disabled=state.powerCooldown>0&&!state.powerCharging;
const dir=state.keys.left?-1:state.keys.right?1:0;p.vx+=(dir*d.speed-p.vx)*.2;if(!dir)p.vx*=.8;p.x=Math.max(0,Math.min(WORLD-80,p.x+p.vx));if(dir)p.face=dir;p.vy+=.68;p.y+=p.vy;const g=ground(p.x);if(p.y+p.h>=g){if(!p.on&&p.vy>7){addParticles(p.x+36,g,10,"dust",.7);setShake(Math.min(4,p.vy*.25))}p.y=g-p.h;p.vy=0;p.on=true;if(state.jumpBuffer>0)tryJump()}else p.on=false;
if(p.vy>=0){for(const plat of platforms){if(p.x+p.w>plat.x&&p.x<plat.x+plat.w&&oldBottom<=plat.y+12&&p.y+p.h>=plat.y){p.y=plat.y-p.h;p.vy=0;p.on=true;if(state.jumpBuffer>0)tryJump();break}}}
if(!state.keys.jump&&p.vy< -5)p.vy*=.82;p.frame+=Math.abs(p.vx)*.065;
for(const b of state.beetles){updateBeetle(b,dt);if(!b.alive)continue;const box={x:b.x-b.w/2,y:b.y,w:b.w,h:b.h};if(overlap(p,box)){const stomping=p.vy>0&&oldBottom<=box.y+12;if(stomping)damageBeetle(b,"stomp",1);else hurt(b.x)}}state.inv=Math.max(0,state.inv-dt);
for(const s of state.blasts){s.x+=s.v;s.life--;const radius=25+s.charge*55,hit={x:s.x-radius,y:s.y-radius*.55,w:radius*2,h:radius*1.1};for(const b of state.beetles){if(!b.alive||b.stun>0)continue;const box={x:b.x-b.w/2,y:b.y,w:b.w,h:b.h};if(overlap(hit,box)){const killed=damageBeetle(b,"blast",s.charge>.82?2:1);s.hits++;if(killed&&s.pierce>1)s.pierce--;else if(s.pierce<=1){s.life=0;break}}}}state.blasts=state.blasts.filter(s=>s.life>0&&s.x>0&&s.x<WORLD);
state.discoveries.forEach((m,i)=>{if(!state.mem[i]&&Math.abs(p.x-m.x)<45)collect(i)});
for(const c of state.crystals){if(!c.got&&Math.abs((p.x+p.w/2)-c.x)<48&&Math.abs((p.y+p.h/2)-c.y)<70){c.got=true;state.score+=750;state.powerCooldown=0;addParticles(c.x,c.y,42,"rainbow",1.2);floater("SECRET CRYSTAL +750",c.x,c.y-35,"combo");setShake(6);syncHud()}}
for(const drop of state.drops){drop.vy+=.22;drop.x+=drop.vx;drop.y+=drop.vy;const dg=ground(drop.x)-18;if(drop.y>dg){drop.y=dg;drop.vy*=-.35}drop.life-=dt;if(overlap(p,{x:drop.x-15,y:drop.y-15,w:30,h:30})){if(drop.type==="heart")state.health=Math.min(state.maxHealth,state.health+1);else{state.score+=250;state.powerCooldown=0}floater(drop.type==="heart"?"+1 HEART":"POWER READY",drop.x,drop.y-20,"combo");drop.life=0;syncHud()}}state.drops=state.drops.filter(d=>d.life>0);
if(p.x>3400&&state.checkpoint<3300){state.checkpoint=3360;ui.checkpoint.classList.remove("hidden");setTimeout(()=>ui.checkpoint.classList.add("hidden"),1900);save()}
if(p.x>6900&&state.checkpoint<6800){state.checkpoint=6820;ui.checkpoint.classList.remove("hidden");setTimeout(()=>ui.checkpoint.classList.add("hidden"),1900);save()}
for(let zi=0;zi<zoneMilestones.length;zi++){const z=zoneMilestones[zi];if(p.x>=z.x&&state.lastZone<zi){state.lastZone=zi;objective(z.t,z.m);floater(z.t.toUpperCase(),p.x,p.y-55,"combo")}}
if(p.x>8900&&!state.portal){if(state.defeated>=state.totalBeetles)finish();else{p.x=8840;objective("The summit is sealed",`Defeat ${state.totalBeetles-state.defeated} more beetle${state.totalBeetles-state.defeated===1?"":"s"}.`)}}
if(state.portal&&p.x>9080){state.complete=true;save();document.body.classList.add("portalExit");setTimeout(()=>location.href="alaska.html",700)}
state.trail.push({x:p.x,y:p.y});if(state.trail.length>70)state.trail.shift();const r=state.trail[Math.max(0,state.trail.length-20)]||{x:p.x-100,y:p.y},z=state.trail[Math.max(0,state.trail.length-42)]||{x:p.x-175,y:p.y};state.rigsby.x+=(r.x-state.rigsby.x)*.12;state.rigsby.y+=(ground(state.rigsby.x)-state.rigsby.h-state.rigsby.y)*.22;state.rigsby.frame+=Math.abs(state.rigsby.x-r.x)*.03;state.zoey.x+=(z.x-state.zoey.x)*.09;state.zoey.y+=(ground(state.zoey.x)-state.zoey.h-state.zoey.y)*.2;
state.camera+=(Math.max(0,Math.min(WORLD-W,p.x-W*.36+p.face*75))-state.camera)*.085;state.shake=Math.max(0,state.shake-dt*.028);state.flash=Math.max(0,state.flash-dt*.0025);ui.trail.style.width=Math.min(100,p.x/(WORLD-250)*100)+"%";ui.altitude.textContent=p.x<1050?"Emerald Shore":p.x<2600?"Whispering Pines":p.x<4050?"Eagle Creek":p.x<5300?"Fallen Timber":p.x<6850?"Crystal Cave":p.x<8200?"Granite Crown":"Infested Summit";
for(const q of state.particles){q.x+=q.vx;q.y+=q.vy;q.vy+=.13;q.life--}state.particles=state.particles.filter(q=>q.life>0);for(const f of state.floaters){f.y-=.55;f.life--}state.floaters=state.floaters.filter(f=>f.life>0)}
function sprite(img,x,y,w,h,frame,face=1){if(!img.complete||!img.naturalWidth){ctx.fillStyle="#ff58ae";ctx.fillRect(x,y,w,h);return}const sw=img.naturalWidth/8;ctx.save();if(face<0){ctx.translate(x+w,y);ctx.scale(-1,1);ctx.drawImage(img,(frame|0)%8*sw,0,sw,img.naturalHeight,0,0,w,h)}else ctx.drawImage(img,(frame|0)%8*sw,0,sw,img.naturalHeight,x,y,w,h);ctx.restore()}
function drawBeetle(b){if(!b.alive)return;const x=b.x-state.camera,y=b.y;ctx.save();ctx.translate(x,y);if(b.flash>0&&Math.floor(b.flash/45)%2===0)ctx.globalAlpha=.35;const armored=b.type==="armored",fly=b.type==="flyer";if(fly){ctx.fillStyle="rgba(220,245,255,.55)";ctx.beginPath();ctx.ellipse(-10,1,18,8,-.4,0,Math.PI*2);ctx.ellipse(10,1,18,8,.4,0,Math.PI*2);ctx.fill()}ctx.fillStyle=armored?"#364d59":"#6b2b1d";ctx.beginPath();ctx.ellipse(0,12,armored?28:23,armored?18:15,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#1d1010";ctx.beginPath();ctx.arc(-22,10,8,0,Math.PI*2);ctx.fill();if(armored){ctx.strokeStyle="#9ec8d2";ctx.lineWidth=4;ctx.beginPath();ctx.arc(3,11,22,Math.PI,Math.PI*2);ctx.stroke()}if(b.alert>.65){ctx.fillStyle="#ffcf5a";ctx.beginPath();ctx.arc(-24,7,2.5,0,Math.PI*2);ctx.fill()}ctx.restore()}
function draw(){ctx.clearRect(0,0,W,H);const sx=(Math.random()-.5)*state.shake,sy=(Math.random()-.5)*state.shake;ctx.save();ctx.translate(sx,sy);let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,"#79cfee");g.addColorStop(.55,"#d2f1ee");g.addColorStop(1,"#3b8c73");ctx.fillStyle=g;ctx.fillRect(-10,-10,W+20,H+20);ctx.fillStyle="#fff3ad";ctx.beginPath();ctx.arc(1070,105,48,0,Math.PI*2);ctx.fill();ctx.fillStyle="rgba(255,255,255,.5)";for(let i=0;i<7;i++){const x=(i*240-state.camera*.07+state.time*.018)%(W+300)-100;ctx.beginPath();ctx.ellipse(x,90+(i%3)*34,78,18,0,0,Math.PI*2);ctx.fill()}ctx.fillStyle="#4b7180";for(let i=0;i<10;i++){const x=i*230-state.camera*.12;ctx.beginPath();ctx.moveTo(x,390);ctx.lineTo(x+120,180+(i%3)*55);ctx.lineTo(x+260,390);ctx.fill()}ctx.fillStyle="#2eaccb";ctx.fillRect(0,365,W,205);for(let i=0;i<14;i++){const y=380+i*12,x=(i*117-state.camera*.28+state.time*.035)%(W+180)-90;ctx.strokeStyle="rgba(235,255,255,.28)";ctx.beginPath();ctx.moveTo(x,y);ctx.quadraticCurveTo(x+45,y-4,x+95,y);ctx.stroke()}ctx.fillStyle="#d4be87";ctx.beginPath();ctx.moveTo(-state.camera,FLOOR);for(let x=0;x<=WORLD;x+=100)ctx.lineTo(x-state.camera,ground(x));ctx.lineTo(WORLD-state.camera,H);ctx.lineTo(-state.camera,H);ctx.fill();
ctx.fillStyle="#3f704b";for(let i=0;i<118;i++){const wx=760+i*72,x=wx-state.camera,y=ground(wx),dead=wx>8100&&i%3===0;ctx.fillStyle=dead?"#75523c":"#3f704b";ctx.beginPath();ctx.moveTo(x,y-145-(i%4)*13);ctx.lineTo(x-40,y);ctx.lineTo(x+40,y);ctx.fill()}
// Waterfall, cave, bridge and overlook landmarks
const fallX=3420-state.camera;ctx.fillStyle="rgba(190,245,255,.72)";ctx.fillRect(fallX,205,72,ground(3420)-205);ctx.fillStyle="rgba(255,255,255,.6)";for(let j=0;j<5;j++)ctx.fillRect(fallX+8+j*13,215,5,ground(3420)-225);
const caveX=6220-state.camera,caveY=ground(6220);ctx.fillStyle="#273a43";ctx.beginPath();ctx.arc(caveX,caveY,130,Math.PI,0);ctx.fill();ctx.fillRect(caveX-130,caveY-10,260,30);ctx.fillStyle="#08151d";ctx.beginPath();ctx.arc(caveX,caveY,82,Math.PI,0);ctx.fill();
for(const plat of platforms){const x=plat.x-state.camera;ctx.fillStyle=plat.kind==="log"||plat.kind==="bridge"?"#7b5135":"#8d9697";ctx.fillRect(x,plat.y,plat.w,plat.h);if(plat.kind==="bridge"){ctx.strokeStyle="#d2aa6e";ctx.lineWidth=4;for(let lx=10;lx<plat.w;lx+=32){ctx.beginPath();ctx.moveTo(x+lx,plat.y);ctx.lineTo(x+lx,plat.y+18);ctx.stroke()}}}
for(const c of state.crystals){if(c.got)continue;const x=c.x-state.camera;ctx.save();ctx.translate(x,c.y);ctx.rotate(state.time*.002);ctx.fillStyle="#79f2ff";ctx.shadowColor="#ff5ac8";ctx.shadowBlur=20;ctx.beginPath();ctx.moveTo(0,-18);ctx.lineTo(13,0);ctx.lineTo(0,20);ctx.lineTo(-13,0);ctx.closePath();ctx.fill();ctx.restore();ctx.shadowBlur=0}
for(const m of state.discoveries){const i=state.discoveries.indexOf(m);if(state.mem[i])continue;const x=m.x-state.camera,y=ground(m.x)-62;ctx.fillStyle="#ffe783";ctx.shadowColor="#ffe783";ctx.shadowBlur=18;ctx.beginPath();ctx.arc(x,y,18+Math.sin(state.time*.006+i)*3,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.font="20px serif";ctx.textAlign="center";ctx.fillText("📸",x,y+7)}for(const b of state.beetles)drawBeetle(b);
for(const s of state.blasts){const x=s.x-state.camera,r=24+s.charge*50;ctx.save();ctx.translate(x,s.y);ctx.globalCompositeOperation="lighter";const rg=ctx.createRadialGradient(0,0,2,0,0,r);rg.addColorStop(0,"#fff");rg.addColorStop(.2,"#ffe76d");rg.addColorStop(.43,"#ff58b9");rg.addColorStop(.7,"#55dcff");rg.addColorStop(1,"rgba(89,255,183,0)");ctx.fillStyle=rg;ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();ctx.restore()}
for(const d of state.drops){const x=d.x-state.camera;ctx.font="26px serif";ctx.textAlign="center";ctx.fillText(d.type==="heart"?"❤️":"🌈",x,d.y+Math.sin(state.time*.01)*4)}for(const q of state.particles){ctx.globalAlpha=Math.max(0,q.life/55);ctx.fillStyle=q.kind==="dust"?"#dcc99d":q.kind==="leaves"?["#5b8f49","#d5a64e","#9b5c38"][Math.floor(q.rot*10)%3]:q.kind==="damage"?"#ff6a77":["#ff5ab7","#ffd95a","#55e0ff","#75ed9b","#a778ff"][Math.floor(q.rot*10)%5];ctx.save();ctx.translate(q.x-state.camera,q.y);ctx.rotate(q.rot);ctx.fillRect(-q.size/2,-q.size/2,q.size,q.size);ctx.restore()}ctx.globalAlpha=1;for(const f of state.floaters){ctx.globalAlpha=Math.max(0,f.life/35);ctx.fillStyle=f.kind==="warning"?"#ffe56f":"#fff";ctx.font="1000 20px system-ui";ctx.textAlign="center";ctx.strokeStyle="rgba(8,20,35,.8)";ctx.lineWidth=5;ctx.strokeText(f.text,f.x-state.camera,f.y);ctx.fillText(f.text,f.x-state.camera,f.y)}ctx.globalAlpha=1;
const zx=state.zoey.x-state.camera,zy=state.zoey.y;ctx.save();ctx.translate(zx,zy);ctx.fillStyle="#f4efe5";ctx.beginPath();ctx.ellipse(34,25,29,17,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#7b4b31";ctx.beginPath();ctx.ellipse(55,16,15,13,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#5a3425";ctx.beginPath();ctx.ellipse(48,8,7,14,-.5,0,Math.PI*2);ctx.ellipse(61,8,7,14,.5,0,Math.PI*2);ctx.fill();ctx.restore();sprite(imgs.rigsby,state.rigsby.x-state.camera,state.rigsby.y,state.rigsby.w,state.rigsby.h,state.rigsby.frame,state.player.face);if(!(state.inv>0&&Math.floor(state.inv/90)%2===0))sprite(imgs[dudes[state.dude].key],state.player.x-state.camera,state.player.y,state.player.w,state.player.h,state.player.frame,state.player.face);
if(state.powerCharging){const p=state.player,x=p.x-state.camera+p.w/2,y=p.y+p.h/2,r=28+state.powerCharge*48;ctx.strokeStyle=`rgba(255,255,255,${.45+state.powerCharge*.45})`;ctx.lineWidth=5;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2*state.powerCharge);ctx.stroke();ctx.strokeStyle="#ff58b8";ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,r+9,Math.PI,Math.PI+Math.PI*2*state.powerCharge);ctx.stroke()}
if(state.portal){const x=9110-state.camera,y=335,p=1+Math.sin(state.time*.008)*.08;ctx.save();ctx.translate(x,y);ctx.scale(p,p);ctx.strokeStyle="#ff58ba";ctx.lineWidth=16;ctx.beginPath();ctx.ellipse(0,0,58,82,0,0,Math.PI*2);ctx.stroke();ctx.strokeStyle="#5de4df";ctx.lineWidth=9;ctx.beginPath();ctx.ellipse(0,0,40,62,0,0,Math.PI*2);ctx.stroke();ctx.restore();ctx.fillStyle="#fff";ctx.font="900 16px system-ui";ctx.textAlign="center";ctx.fillText("ALASKA",x,y-105)}ctx.restore();if(state.flash>0){ctx.fillStyle=`rgba(255,255,255,${state.flash})`;ctx.fillRect(0,0,W,H)}if(!state.started){ctx.fillStyle="rgba(2,15,28,.25)";ctx.fillRect(0,0,W,H)}}
function release(){if(state.powerCharging)releaseCharge();for(const k in state.keys)state.keys[k]=false}
document.querySelectorAll("[data-action]").forEach(b=>{const a=b.dataset.action;b.addEventListener("pointerdown",e=>{e.preventDefault();if(!state.started||state.paused)return;press(a,true);b.classList.add("isPressed");try{b.setPointerCapture(e.pointerId)}catch(_){}},{passive:false});const up=e=>{e.preventDefault();press(a,false);b.classList.remove("isPressed")};b.addEventListener("pointerup",up,{passive:false});b.addEventListener("pointercancel",up,{passive:false});b.addEventListener("lostpointercapture",up)});
function keyAction(e){return e.code==="ArrowLeft"||e.code==="KeyA"?"left":e.code==="ArrowRight"||e.code==="KeyD"?"right":e.code==="ArrowUp"||e.code==="KeyW"||e.code==="Space"?"jump":e.code==="KeyX"||e.code==="KeyF"?"power":""}
addEventListener("keydown",e=>{const a=keyAction(e);if(a){e.preventDefault();if(!e.repeat||a==="left"||a==="right")press(a,true)}});addEventListener("keyup",e=>{const a=keyAction(e);if(a){e.preventDefault();press(a,false)}});addEventListener("blur",release);
ui.begin.addEventListener("click",()=>reset(false));ui.switch.addEventListener("click",()=>setDude(state.dude+1));ui.pauseBtn.addEventListener("click",()=>{if(!state.started)return;state.paused=!state.paused;ui.pause.classList.toggle("hidden",!state.paused);if(state.paused)release()});ui.resume.addEventListener("click",()=>{state.paused=false;ui.pause.classList.add("hidden")});ui.restart.addEventListener("click",()=>reset(true));ui.replay.addEventListener("click",()=>reset(true));ui.continuePortal.addEventListener("click",()=>{state.portal=true;state.player.x=8840;state.player.y=ground(8840)-state.player.h;ui.trailhead.classList.add("hidden")});
let last=performance.now();function loop(now){const dt=Math.min(32,now-last);last=now;try{update(dt);draw()}catch(err){console.error("Tahoe 2.3 recovered:",err);objective("Tahoe recovered","Press Restart Tahoe if controls stop.")}requestAnimationFrame(loop)}requestAnimationFrame(loop);
window.__TAHOE_RELEASE__={version:RELEASE,name:"Living Tahoe World",features:["9200px expanded trail","five secret crystals","climbable ledges","waterfall","fallen timber bridge","crystal cave","granite overlook","six memories","two checkpoints","18 beetles","zone milestones","Superman combat retained"]};
})();
