(() => {
"use strict";
const $=id=>document.getElementById(id), canvas=$("tahoeCanvas"), ctx=canvas.getContext("2d");
const W=canvas.width,H=canvas.height,WORLD=9800,FLOOR=570,SAVE="3dudes1quest_tahoe_v250",RELEASE="2.5.3";
const platforms=[
{x:1320,y:438,w:190,h:18,kind:"log"},{x:1580,y:385,w:170,h:18,kind:"rock"},{x:1840,y:330,w:190,h:18,kind:"rock"},
{x:2800,y:410,w:180,h:18,kind:"log"},{x:3060,y:350,w:170,h:18,kind:"rock"},{x:3320,y:292,w:210,h:18,kind:"rock"},
{x:4100,y:420,w:220,h:18,kind:"bridge"},{x:4350,y:420,w:220,h:18,kind:"bridge"},{x:4600,y:420,w:220,h:18,kind:"bridge"},
{x:5480,y:385,w:180,h:18,kind:"rock"},{x:5740,y:325,w:170,h:18,kind:"rock"},{x:6000,y:265,w:210,h:18,kind:"rock"},
{x:7050,y:400,w:190,h:18,kind:"log"},{x:7330,y:335,w:180,h:18,kind:"rock"},{x:7610,y:270,w:210,h:18,kind:"lookout"}
];
const nests=[
{targetKind:"nest",x:2250,y:0,w:88,h:116,hp:3,maxHp:3,alive:true,spawned:0,timer:900},
{targetKind:"nest",x:4720,y:0,w:88,h:116,hp:4,maxHp:4,alive:true,spawned:0,timer:700},
{targetKind:"nest",x:6380,y:0,w:88,h:116,hp:4,maxHp:4,alive:true,spawned:0,timer:620},
{targetKind:"nest",x:8020,y:0,w:88,h:116,hp:5,maxHp:5,alive:true,spawned:0,timer:520}
];
const zoneMilestones=[{x:1050,t:"Whispering Pines",m:"Climb above Emerald Shore."},{x:2600,t:"Eagle Creek",m:"Cross the waterfall ledges."},{x:4050,t:"Fallen Timber Crossing",m:"Fight across the broken log bridge."},{x:5300,t:"Crystal Cave",m:"Take the high path through the hidden cave."},{x:6850,t:"Granite Crown",m:"Climb to Tahoe's highest overlook."},{x:8200,t:"Infested Summit",m:"Clear the final beetle colony."}];
const ui={opening:$("openingCard"),begin:$("beginTahoe"),mission:$("missionCard"),tip:$("playTip"),input:$("inputStatus"),pause:$("pauseMenu"),pauseBtn:$("pauseBtn"),resume:$("resumeTahoe"),restart:$("restartTahoe"),replay:$("replayTahoe"),switch:$("switchBtn"),power:$("powerBtn"),trail:$("trailProgressFill"),health:$("hudHealth"),beetles:$("hudBeetles"),memories:$("hudMemories"),altitude:$("hudAltitude"),dude:$("hudDude"),portrait:$("hudPortrait"),objectiveTitle:$("objectiveTitle"),objectiveText:$("objectiveText"),memory:$("memoryCard"),memoryTitle:$("memoryCardTitle"),memoryText:$("memoryCardText"),checkpoint:$("checkpointCard"),finale:$("finaleBanner"),trailhead:$("trailheadCard"),continuePortal:$("continueToPortal"),cinematic:$("cinematicCaption"),dialogue:$("dialogue"),combo:$("comboHud"),score:$("hudScore"),powerFill:$("powerChargeFill"),powerLabel:$("powerChargeLabel"),nests:$("hudNests"),bossWrap:$("bossHud"),bossFill:$("bossHealthFill"),bossPhase:$("bossPhase"),weather:$("hudWeather")};
const dudes=window.QuestCore?.CAST;
if(!dudes)throw new Error("QuestCore must load before Adventure 2");
const imgs=window.QuestCore.loadCastImages();
let castReady=false;
let castLoadReport=null;
const makeBeetle=(x,type="walker",min=x-120,max=x+120)=>({targetKind:"beetle",x,y:0,w:type==="armored"?58:48,h:type==="flyer"?34:30,v:type==="charger"?1.2:1.45,min,max,alive:true,type,hp:type==="armored"?2:1,flash:0,stun:0,alert:0,phase:Math.random()*6.28});
const state={started:false,paused:false,complete:false,finale:false,portal:false,forestRestored:false,weather:"sun",weatherTimer:0,barkCooldown:0,nestsDestroyed:0,bossStarted:false,bossDefeated:false,boss:{targetKind:"boss",x:9000,y:260,w:190,h:150,hp:18,maxHp:18,phase:1,alive:true,flash:0,inv:0,vx:-1.4,vy:0,attackTimer:1200,spawnTimer:1900},keys:{left:false,right:false,jump:false,power:false},player:{x:250,y:FLOOR-72,w:44,h:72,vx:0,vy:0,on:true,face:1,frame:0,anim:"idle",animUntil:0},rigsby:{x:140,y:FLOOR-40,w:56,h:40,frame:0},zoey:{x:70,y:FLOOR-38,w:54,h:38},camera:0,dude:0,health:4,maxHealth:4,defeated:0,totalBeetles:18,mem:[false,false,false,false,false,false],checkpoint:250,lastZone:-1,inv:0,heroShots:[],cookieBombs:[],positiveFields:[],particles:[],floaters:[],drops:[],trail:[],crystals:[{x:1700,y:290,got:false},{x:3180,y:310,got:false},{x:4490,y:365,got:false},{x:5940,y:220,got:false},{x:7480,y:290,got:false}],time:0,coyote:0,jumpBuffer:0,powerHeld:false,combo:0,comboTimer:0,score:0,shake:0,flash:0,hitStop:0,danielCast:0,beetles:[
makeBeetle(1180),makeBeetle(1480,"charger"),makeBeetle(1780,"flyer"),makeBeetle(2180,"walker"),
makeBeetle(2670,"armored"),makeBeetle(3020,"charger"),makeBeetle(3420,"flyer"),makeBeetle(3820,"walker"),
makeBeetle(4250,"charger"),makeBeetle(4680,"armored"),makeBeetle(5120,"flyer"),makeBeetle(5560,"walker"),
makeBeetle(6120,"armored"),makeBeetle(6580,"charger"),makeBeetle(7110,"flyer"),makeBeetle(7620,"walker"),
makeBeetle(8240,"charger"),makeBeetle(8660,"armored")],discoveries:[
{x:900,t:"SUNRISE AT THE LAKE",d:"The water like glass before the world wakes."},
{x:2450,t:"RIGSBY'S TAHOE DAYS",d:"Cold paws, brave swimming, pure beagle joy."},
{x:3900,t:"THE FALLEN TIMBER",d:"Every storm leaves a new path forward."},
{x:5350,t:"CRYSTAL CAVE",d:"Tahoe keeps entire worlds hidden beneath the granite."},
{x:6900,t:"TAHOE IN WINTER",d:"Snow on every branch and frozen mountain air."},
{x:8050,t:"THE OVERLOOK",d:"Sixteen years here and still something new."}]};
function ground(x){
if(x<1000)return FLOOR;
if(x<2400)return 560-Math.min(75,(x-1000)*.045)+Math.sin(x/170)*8;
if(x<3900)return 500-Math.sin((x-2400)/190)*24;
if(x<5000)return 525+Math.sin((x-3900)/155)*18;
if(x<6500)return 505-Math.min(95,(x-5000)*.05)+Math.sin(x/160)*10;
if(x<8100)return 440-Math.sin((x-6500)/175)*22;
return 430-Math.min(55,(x-8100)*.045)+Math.sin(x/130)*7
}
function overlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function objective(a,b){ui.objectiveTitle.textContent=a;ui.objectiveText.textContent=b}
function inputLabel(t){if(!ui.input)return;ui.input.querySelector("b").textContent=t;ui.input.classList.add("active");clearTimeout(inputLabel.t);inputLabel.t=setTimeout(()=>{ui.input.classList.remove("active");ui.input.querySelector("b").textContent="READY"},600)}
function setDude(n){
state.dude=(n+3)%3;const d=dudes[state.dude];ui.dude.textContent=d.name;ui.portrait.textContent=d.letter;
const icon=$("powerIcon"),label=$("powerButtonLabel");if(icon)icon.textContent=d.powerIcon;if(label)label.textContent="POWER";
if(ui.power)ui.power.setAttribute("aria-label",`Use ${d.power}`);ui.powerFill.style.width="100%";ui.powerLabel.textContent=d.power.toUpperCase();
inputLabel(`${d.name.toUpperCase()} READY • ${d.power.toUpperCase()}`)
}
function addParticles(x,y,count,kind="rainbow",power=1){for(let i=0;i<count;i++)state.particles.push({x,y,vx:(Math.random()-.5)*7*power,vy:(Math.random()-.8)*7*power,life:28+Math.random()*38,size:2+Math.random()*5,kind,rot:Math.random()*6.28})}
function floater(text,x,y,kind="score"){state.floaters.push({text,x,y,life:70,kind})}
function setShake(n){state.shake=Math.max(state.shake,n)}
function save(){try{localStorage.setItem(SAVE,JSON.stringify({checkpoint:state.checkpoint,defeated:state.defeated,alive:state.beetles.map(b=>b.alive),hp:state.beetles.map(b=>b.hp),mem:state.mem,dude:state.dude,score:state.score,maxHealth:state.maxHealth,nests:nests.map(n=>({alive:n.alive,hp:n.hp,spawned:n.spawned})),nestsDestroyed:state.nestsDestroyed,boss:state.boss,bossDefeated:state.bossDefeated,forestRestored:state.forestRestored}))}catch(_) {}}
function load(){try{const d=JSON.parse(localStorage.getItem(SAVE)||"null");if(!d)return;state.checkpoint=Number(d.checkpoint)||250;state.defeated=Math.min(state.totalBeetles,Number(d.defeated)||0);if(Array.isArray(d.alive))state.beetles.forEach((b,i)=>b.alive=d.alive[i]!==false);if(Array.isArray(d.hp))state.beetles.forEach((b,i)=>b.hp=Number(d.hp[i])||b.hp);if(Array.isArray(d.mem))state.mem=d.mem.slice(0,6).map(Boolean);state.score=Number(d.score)||0;state.maxHealth=4;state.health=4;if(Array.isArray(d.nests))nests.forEach((n,i)=>{const s=d.nests[i];if(s){n.alive=s.alive!==false;n.hp=Number(s.hp)||n.hp;n.spawned=Number(s.spawned)||0}});state.nestsDestroyed=Number(d.nestsDestroyed)||nests.filter(n=>!n.alive).length;if(d.boss&&typeof d.boss==="object")Object.assign(state.boss,d.boss);state.bossDefeated=!!d.bossDefeated;state.forestRestored=!!d.forestRestored;setDude(Number(d.dude)||0);state.player.x=state.checkpoint;state.player.y=ground(state.player.x)-state.player.h;syncHud()}catch(_) {}}
function syncHud(){ui.health.textContent=`${state.health}/${state.maxHealth}`;ui.beetles.textContent=state.defeated;ui.memories.textContent=state.mem.filter(Boolean).length;ui.score.textContent=state.score.toLocaleString();ui.combo.textContent=state.combo>1?`${state.combo}x COMBO`:"";ui.combo.classList.toggle("show",state.combo>1);if(ui.nests)ui.nests.textContent=state.nestsDestroyed;if(ui.bossWrap){ui.bossWrap.classList.toggle("hidden",!state.bossStarted||state.bossDefeated);ui.bossFill.style.width=`${Math.max(0,state.boss.hp/state.boss.maxHp*100)}%`;ui.bossPhase.textContent=`PHASE ${state.boss.phase}`;}if(ui.weather)ui.weather.textContent=state.weather.toUpperCase()}
function reset(clear=false){
if(!castReady){objective("Loading the locked Adventure 1 cast","Will, Daniel, Caleb, and Rigsby must finish loading before Tahoe begins.");return;}
if(clear)try{localStorage.removeItem(SAVE)}catch(_){}
Object.assign(state.player,{x:250,y:FLOOR-72,vx:0,vy:0,on:true,face:1,frame:0,anim:"idle",animUntil:0});
Object.assign(state,{camera:0,started:true,paused:false,complete:false,finale:false,portal:false,health:state.maxHealth,defeated:0,mem:[false,false,false,false,false,false],checkpoint:250,lastZone:-1,heroShots:[],cookieBombs:[],positiveFields:[],particles:[],floaters:[],drops:[],trail:[],crystals:[{x:1700,y:290,got:false},{x:3180,y:310,got:false},{x:4490,y:365,got:false},{x:5940,y:220,got:false},{x:7480,y:290,got:false}],combo:0,comboTimer:0,score:0,powerHeld:false,shake:0,flash:0,hitStop:0,danielCast:0,forestRestored:false,weather:"sun",weatherTimer:0,barkCooldown:0,nestsDestroyed:0,bossStarted:false,bossDefeated:false});
nests.forEach(n=>{n.alive=true;n.hp=n.maxHp;n.spawned=0;n.timer=700});
Object.assign(state.boss,{targetKind:"boss",x:9000,y:260,hp:18,maxHp:18,phase:1,alive:true,flash:0,inv:0,vx:-1.4,vy:0,attackTimer:1200,spawnTimer:1900});
state.beetles=[makeBeetle(1180),makeBeetle(1480,"charger"),makeBeetle(1780,"flyer"),makeBeetle(2180),makeBeetle(2670,"armored"),makeBeetle(3020,"charger"),makeBeetle(3420,"flyer"),makeBeetle(3820),makeBeetle(4250,"charger"),makeBeetle(4680,"armored"),makeBeetle(5120,"flyer"),makeBeetle(5560),makeBeetle(6120,"armored"),makeBeetle(6580,"charger"),makeBeetle(7110,"flyer"),makeBeetle(7620),makeBeetle(8240,"charger"),makeBeetle(8660,"armored")];state.totalBeetles=18;
setDude(0);if(!clear)load();ui.opening.classList.add("hidden");ui.pause.classList.add("hidden");ui.trailhead.classList.add("hidden");ui.finale.classList.add("hidden");ui.dialogue.classList.add("hidden");ui.cinematic.classList.add("hidden");ui.mission.classList.remove("hidden");setTimeout(()=>ui.mission.classList.add("hidden"),2400);ui.tip.classList.remove("hidden");setTimeout(()=>ui.tip.classList.add("hidden"),6000);objective("Explore the expanded Tahoe trail","Use the same cast, controls and powers from Adventure 1.");syncHud();canvas.focus({preventScroll:true})
}
function press(action,value){
if(action==="power"&&value&&!state.keys.power)firePower();
if(action==="jump"&&value&&!state.keys.jump){state.jumpBuffer=155;tryJump()}
state.keys[action]=value
}
function tryJump(){if(!state.started||state.paused||state.complete)return;if(state.player.on||state.coyote>0){state.player.vy=-dudes[state.dude].jump;state.player.on=false;state.coyote=0;state.jumpBuffer=0;addParticles(state.player.x+22,state.player.y+state.player.h,8,"dust",.55);inputLabel("JUMP")}}
function firePower(){
if(!state.started||state.paused||state.complete)return;
const payload=window.QuestCore.makePowerProjectile(state.dude,state.player);
if(payload.kind==="heroShot")state.heroShots.push(payload.entity);else state.cookieBombs.push(payload.entity);
state.player.anim="attack";state.player.animUntil=state.time+430;
if(state.dude===1){state.danielCast=12;state.inv=Math.max(state.inv,42)}
addParticles(state.player.x+22,state.player.y+34,state.dude===0?18:10,state.dude===1?"heart":state.dude===2?"cookie":"rainbow",.85);setShake(state.dude===0?5:2);inputLabel(payload.feedback.toUpperCase());
ui.power.classList.add("powerReadyPulse");setTimeout(()=>ui.power.classList.remove("powerReadyPulse"),180)
}
function comboHit(x,y,base=100){state.combo=state.comboTimer>0?state.combo+1:1;state.comboTimer=1800;const points=base*state.combo;state.score+=points;floater(state.combo>1?`${state.combo}x +${points}`:`+${points}`,x,y,"combo");syncHud()}
function damageBeetle(b,mode,power=1){if(!b.alive||b.stun>0)return false;b.hp-=power;b.flash=160;b.stun=140;if(b.hp>0){floater("CRACK!",b.x,b.y-28,"warning");setShake(5);return false}defeat(b,mode);return true}
function defeat(b,mode){if(!b.alive)return;b.alive=false;state.defeated++;comboHit(b.x,b.y-20,100);addParticles(b.x,b.y,28,"leaves",1.1);addParticles(b.x,b.y,18,mode==="heart"?"heart":mode==="cookie"?"cookie":"rainbow",.9);setShake(6);state.hitStop=40;if(Math.random()<.28)state.drops.push({x:b.x,y:b.y-20,vx:(Math.random()-.5)*2,vy:-5,type:Math.random()<.42?"heart":"crystal",life:900});objective(state.defeated<state.totalBeetles?"Keep clearing beetles":"Reach the summit",state.defeated<state.totalBeetles?`${state.totalBeetles-state.defeated} beetles remaining.`:"The summit portal is awakening.");syncHud();save()}
function hurt(sourceX){if(state.inv>0||state.complete)return;state.health--;state.inv=1100;state.player.anim="hurt";state.player.animUntil=state.time+430;state.combo=0;state.comboTimer=0;state.player.vy=-8.5;state.player.vx=state.player.x<sourceX?-8:8;state.flash=.48;setShake(10);addParticles(state.player.x+36,state.player.y+48,18,"damage",1);if(state.health<=0){state.health=state.maxHealth;state.player.x=state.checkpoint;state.player.y=ground(state.player.x)-state.player.h;state.player.vx=state.player.vy=0;objective("Back at the checkpoint","Keep fighting. Your progress is safe.")}syncHud()}
function collect(i){if(state.mem[i])return;state.mem[i]=true;state.score+=500;ui.memoryTitle.textContent=state.discoveries[i].t;ui.memoryText.textContent=state.discoveries[i].d;ui.memory.classList.remove("hidden");setTimeout(()=>ui.memory.classList.add("hidden"),2600);addParticles(state.discoveries[i].x,ground(state.discoveries[i].x)-60,38,"rainbow",1);floater("MEMORY +500",state.discoveries[i].x,ground(state.discoveries[i].x)-90,"combo");syncHud();save()}
function damageNest(n,power=1){if(!n.alive)return false;n.hp-=power;addParticles(n.x,n.y-45,18,"leaves",1);setShake(5);floater(n.hp>0?`NEST ${n.hp}/${n.maxHp}`:"NEST DESTROYED!",n.x,n.y-90,n.hp>0?"warning":"combo");if(n.hp<=0){n.alive=false;state.nestsDestroyed++;state.score+=1000;addParticles(n.x,n.y-45,50,"rainbow",1.3);state.flash=.3;syncHud();save()}return !n.alive}
function updateNests(dt){for(const n of nests){n.y=ground(n.x);if(!n.alive)continue;n.timer-=dt;if(n.timer<=0&&n.spawned<3&&Math.abs(state.player.x-n.x)<720){const t=n.spawned===2?"armored":n.spawned===1?"flyer":"charger";const b=makeBeetle(n.x+(Math.random()-.5)*160,t,n.x-220,n.x+220);state.beetles.push(b);state.totalBeetles++;n.spawned++;n.timer=1700;floater("THE NEST HATCHES!",n.x,n.y-110,"warning");syncHud()}}}
function hitBoss(power=1,mode="blast"){const b=state.boss;if(!b.alive||b.inv>0)return false;b.hp-=power;b.flash=180;b.inv=120;setShake(7+power*2);addParticles(b.x,b.y+70,20,"rainbow",1);floater(mode==="heart"?"HEARTFIELD HIT!":mode==="cookie"?"COOKIE BLAST!":"RAINBOW HIT!",b.x,b.y-35,"combo");if(b.hp<=12&&b.phase<2){b.phase=2;b.attackTimer=500;floater("PHASE 2 — THE QUEEN TAKES FLIGHT",b.x,b.y-70,"warning")}if(b.hp<=6&&b.phase<3){b.phase=3;b.attackTimer=300;state.weather="storm";floater("PHASE 3 — FULL CORRUPTION",b.x,b.y-70,"warning")}if(b.hp<=0){b.alive=false;state.bossDefeated=true;state.forestRestored=true;state.weather="rainbow";state.score+=5000;state.flash=.85;setShake(18);addParticles(b.x,b.y+70,120,"rainbow",1.8);floater("PINE BEETLE QUEEN DEFEATED!",b.x,b.y-90,"combo");objective("Tahoe is breathing again","Walk to the restored summit and enter the Alaska portal.");state.portal=true;syncHud();save()}return !b.alive}
function updateBoss(dt){const b=state.boss;if(!state.bossStarted||!b.alive)return;b.inv=Math.max(0,b.inv-dt);b.flash=Math.max(0,b.flash-dt);b.attackTimer-=dt;b.spawnTimer-=dt;const p=state.player;if(b.phase===1){b.y=ground(b.x)-b.h;b.x+=b.vx;if(b.x<8520||b.x>9360)b.vx*=-1}else{b.y=255+Math.sin(state.time*.006)*(b.phase===3?95:65);b.x+=Math.sign(p.x-b.x)*(b.phase===3?2.2:1.25)}if(b.attackTimer<=0){if(b.phase===1){const dir=Math.sign(p.x-b.x)||-1;b.vx=dir*5.5;floater("QUEEN CHARGE!",b.x,b.y-20,"warning");b.attackTimer=1250}else{state.drops.push({x:b.x,y:b.y+90,vx:(Math.random()-.5)*3,vy:2.5,type:"hazard",life:2600});floater(b.phase===3?"CORRUPTION BOMB!":"LARVA DROP!",b.x,b.y-25,"warning");b.attackTimer=b.phase===3?600:950}}if(b.spawnTimer<=0&&b.phase>=2){const minion=makeBeetle(b.x+(Math.random()-.5)*120,b.phase===3?"armored":"flyer",b.x-260,b.x+260);state.beetles.push(minion);state.totalBeetles++;b.spawnTimer=b.phase===3?1500:2400;syncHud()}const box={x:b.x-b.w/2,y:b.y,w:b.w,h:b.h};if(overlap(p,box))hurt(b.x)}
function targetAlive(target){return !!target&&target.alive!==false}
function targetRect(target){if(target.targetKind==="beetle")return{x:target.x-target.w/2,y:target.y,w:target.w,h:target.h};if(target.targetKind==="nest")return{x:target.x-target.w/2,y:target.y-target.h+8,w:target.w,h:target.h};if(target.targetKind==="boss")return{x:target.x-target.w/2,y:target.y,w:target.w,h:target.h};return target}
function targetCenter(target){const r=targetRect(target);return{x:r.x+r.w/2,y:r.y+r.h/2}}
function activeTargets(){const list=[...state.beetles.filter(b=>b.alive),...nests.filter(n=>n.alive)];if(state.bossStarted&&state.boss.alive)list.push(state.boss);return list}
function damageTarget(target,amount,source){if(target.targetKind==="beetle")return damageBeetle(target,source,amount);if(target.targetKind==="nest")return damageNest(target,amount);if(target.targetKind==="boss")return hitBoss(amount,source);return false}
function findRicochetTarget(shot,from){let best=null,bestDistance=window.QuestCore.POWER_CONTRACT.rainbow.maxTargetRange**2;const origin=targetCenter(from);for(const target of activeTargets()){if(shot.hitTargets.includes(target))continue;const center=targetCenter(target),dx=center.x-origin.x,dy=center.y-origin.y,distance=dx*dx+dy*dy;if(distance<bestDistance){bestDistance=distance;best=target}}return best}
function redirectRicochet(shot,from){if(shot.bounces<=0)return false;const target=findRicochetTarget(shot,from);if(!target)return false;const origin=targetCenter(from),center=targetCenter(target),dx=center.x-origin.x,dy=center.y-origin.y,len=Math.max(1,Math.hypot(dx,dy));shot.x=origin.x-shot.w/2;shot.y=origin.y-shot.h/2;shot.vx=dx/len*13.4;shot.vy=dy/len*13.4;shot.bounces--;shot.life=Math.max(shot.life,48);addParticles(shot.x+shot.w/2,shot.y+shot.h/2,20,"rainbow",.8);return true}
function spawnPositiveField(target){if(state.positiveFields.some(field=>field.target===target&&!field.detonated))return;const center=targetCenter(target);state.positiveFields.push({x:center.x,y:center.y,target,life:62,maxLife:62,age:0,radius:20,detonated:false});if(target.targetKind==="beetle")target.stun=Math.max(target.stun||0,62);addParticles(center.x,center.y,38,"heart",1);setShake(6);inputLabel(target.targetKind==="boss"?"QUEEN TRAPPED IN A HEARTFIELD!":"HEARTFIELD LOCKED!")}
function updateHeroShots(dt){const step=dt/16.667;for(const shot of state.heroShots){shot.age=(shot.age||0)+step;shot.trail.push({x:shot.x,y:shot.y});if(shot.trail.length>(shot.type==="heart"?15:13))shot.trail.shift();if(shot.type==="heart"){let target=null,best=Infinity;for(const candidate of activeTargets()){const center=targetCenter(candidate);if(!((shot.vx>0&&center.x>shot.x-35)||(shot.vx<0&&center.x<shot.x+35)))continue;if(Math.abs(center.x-shot.x)>620)continue;const dx=center.x-(shot.x+shot.w/2),dy=center.y-(shot.y+shot.h/2),distance=dx*dx+dy*dy;if(distance<best){best=distance;target=candidate}}if(target){const center=targetCenter(target),targetY=center.y-shot.h/2;shot.vy+=(targetY-shot.y)*.018*step;shot.vy=Math.max(-4.2,Math.min(4.2,shot.vy));shot.vx+=Math.sign(center.x-(shot.x+shot.w/2))*.08*step;shot.vx=Math.max(-12.5,Math.min(12.5,shot.vx))}}
shot.x+=shot.vx*step;shot.y+=(shot.vy||0)*step;shot.life-=step;for(const target of activeTargets()){if(shot.hitTargets?.includes(target)||!overlap(shot,targetRect(target)))continue;if(shot.type==="heart"){shot.life=0;spawnPositiveField(target)}else{shot.hitTargets.push(target);damageTarget(target,1,"rainbow");if(!redirectRicochet(shot,target))shot.life=0}break}}
state.heroShots=state.heroShots.filter(shot=>shot.life>0&&shot.x>-100&&shot.x<WORLD+100&&shot.y>-120&&shot.y<H+120)}
function updatePositiveFields(dt){const step=dt/16.667;for(const field of state.positiveFields){field.age+=step;field.life-=step;if(targetAlive(field.target)){const center=targetCenter(field.target);field.x=center.x;field.y=center.y;if(field.target.targetKind==="beetle")field.target.stun=Math.max(field.target.stun||0,120)}field.radius=20+Math.sin(Math.min(1,field.age/30)*Math.PI/2)*78;if(!field.detonated&&field.age>=30){field.detonated=true;setShake(13);addParticles(field.x,field.y,82,"heart",1.2);if(targetAlive(field.target)){if(field.target.targetKind==="beetle")field.target.stun=0;damageTarget(field.target,field.target.targetKind==="nest"?2:1,"heart");}for(const candidate of activeTargets()){if(candidate===field.target)continue;const center=targetCenter(candidate);if(Math.hypot(center.x-field.x,center.y-field.y)<135)damageTarget(candidate,1,"heart")}inputLabel("HEARTFIELD BURST!")}}
state.positiveFields=state.positiveFields.filter(field=>field.life>0)}
function updateCookieBombs(dt){const step=dt/16.667;for(const bomb of state.cookieBombs){if(bomb.stuck){bomb.fuse-=step;bomb.life-=step;if(targetAlive(bomb.target)){const center=targetCenter(bomb.target);bomb.x=center.x-bomb.w/2;bomb.y=center.y-bomb.h/2}else bomb.target=null;if(bomb.fuse<=0){bomb.life=0;explodeCookie(bomb.x+bomb.w/2,bomb.y+bomb.h/2)}continue}bomb.trail.push({x:bomb.x+bomb.w/2,y:bomb.y+bomb.h/2});if(bomb.trail.length>12)bomb.trail.shift();bomb.x+=bomb.vx*step;bomb.y+=bomb.vy*step;bomb.vy+=(bomb.gravity??.28)*step;bomb.life-=step;let target=null;for(const candidate of activeTargets()){if(overlap(bomb,targetRect(candidate))){target=candidate;break}}if(target){bomb.stuck=true;bomb.target=target;bomb.vx=bomb.vy=0;bomb.fuse=34;if(target.targetKind==="beetle")target.stun=Math.max(target.stun||0,34);inputLabel("COOKIE STUCK!");addParticles(bomb.x,bomb.y,18,"cookie",.8);continue}const floor=ground(bomb.x);if(bomb.y+bomb.h>=floor){bomb.y=floor-bomb.h;bomb.vx=bomb.vy=0;bomb.stuck=true;bomb.fuse=30;inputLabel("COOKIE ARMED!")}if(bomb.life<=0){bomb.life=0;explodeCookie(bomb.x+bomb.w/2,bomb.y+bomb.h/2)}}state.cookieBombs=state.cookieBombs.filter(bomb=>bomb.life>0)}
function explodeCookie(x,y){for(const target of activeTargets())if(target.targetKind==="beetle")target.stun=0;setShake(15);addParticles(x,y,82,"cookie",1.25);for(const target of activeTargets()){const center=targetCenter(target),radius=target.targetKind==="boss"?280:220;if(Math.hypot(center.x-x,center.y-y)<radius)damageTarget(target,2,"cookie")}inputLabel("COOKIE EXPLOSION!")}
function updateWeather(dt){state.weatherTimer+=dt;const x=state.player.x;if(state.forestRestored)state.weather="rainbow";else if(state.bossStarted)state.weather=state.boss.phase===3?"storm":"rain";else if(x>7600)state.weather="storm";else if(x>5200)state.weather="rain";else if(x>2600)state.weather="clouds";else state.weather="sun";if(ui.weather)ui.weather.textContent=state.weather.toUpperCase()}
function rigsbySense(dt){state.barkCooldown=Math.max(0,state.barkCooldown-dt);if(state.barkCooldown>0)return;const p=state.player;const secret=state.crystals.find(c=>!c.got&&Math.abs(c.x-p.x)<260);const nest=nests.find(n=>n.alive&&Math.abs(n.x-p.x)<300);if(secret||nest){floater(secret?"RIGSBY: BARK! SECRET NEARBY":"RIGSBY: GRRR... NEST NEARBY",state.rigsby.x,state.rigsby.y-25,"warning");state.barkCooldown=4200}}
function finish(){if(state.finale)return;state.finale=true;state.portal=true;ui.finale.classList.remove("hidden");objective("Enter the Alaska Portal","Walk into the glowing portal at the summit.");setTimeout(()=>ui.finale.classList.add("hidden"),3200)}
function updateBeetle(b,dt){if(!b.alive)return;b.flash=Math.max(0,b.flash-dt);b.stun=Math.max(0,b.stun-dt);if(b.stun>0)return;const p=state.player,dist=p.x-b.x;b.alert=Math.abs(dist)<330?Math.min(1,b.alert+dt*.004):Math.max(0,b.alert-dt*.0015);if(b.type==="flyer"){b.x+=b.v*(1+b.alert*.5);if(b.x<b.min||b.x>b.max)b.v*=-1;b.y=ground(b.x)-125+Math.sin(state.time*.006+b.phase)*42}else{const chase=b.alert>0.55?Math.sign(dist):Math.sign(b.v);let speed=Math.abs(b.v);if(b.type==="charger"&&b.alert>.72)speed=4.4;b.x+=chase*speed;if(b.x<b.min||b.x>b.max){b.x=Math.max(b.min,Math.min(b.max,b.x));b.v*=-1}b.y=ground(b.x)-b.h}}
function update(dt){
if(!state.started||state.paused||state.complete)return;if(state.hitStop>0){state.hitStop-=dt;return}
state.time+=dt;const p=state.player,d=dudes[state.dude],oldBottom=p.y+p.h;state.coyote=p.on?125:Math.max(0,state.coyote-dt);state.jumpBuffer=Math.max(0,state.jumpBuffer-dt);state.comboTimer=Math.max(0,state.comboTimer-dt);if(state.comboTimer===0&&state.combo){state.combo=0;syncHud()}ui.powerFill.style.width="100%";ui.powerLabel.textContent=d.power.toUpperCase();ui.power.disabled=false;
const dir=state.keys.left?-1:state.keys.right?1:0;p.vx+=(dir*d.speed-p.vx)*.2;if(!dir)p.vx*=.8;p.x=Math.max(0,Math.min(WORLD-p.w,p.x+p.vx));if(dir)p.face=dir;p.vy+=.68;p.y+=p.vy;const g=ground(p.x);if(p.y+p.h>=g){if(!p.on&&p.vy>7){addParticles(p.x+22,g,10,"dust",.7);setShake(Math.min(4,p.vy*.25))}p.y=g-p.h;p.vy=0;p.on=true;if(state.jumpBuffer>0)tryJump()}else p.on=false;
if(p.vy>=0){for(const platform of platforms){if(p.x+p.w>platform.x&&p.x<platform.x+platform.w&&oldBottom<=platform.y+12&&p.y+p.h>=platform.y){p.y=platform.y-p.h;p.vy=0;p.on=true;if(state.jumpBuffer>0)tryJump();break}}}
if(!state.keys.jump&&p.vy<-5)p.vy*=.82;p.frame+=Math.abs(p.vx)*.065;if(p.animUntil<=state.time)p.anim=!p.on?"jump":Math.abs(p.vx)>.35?"walk":"idle";state.danielCast=Math.max(0,state.danielCast-dt);
for(const beetle of state.beetles){updateBeetle(beetle,dt);if(!beetle.alive)continue;if(overlap(p,targetRect(beetle)))hurt(beetle.x)}state.inv=Math.max(0,state.inv-dt);updateNests(dt);updateWeather(dt);rigsbySense(dt);
if(p.x>8420&&!state.bossStarted){if(state.nestsDestroyed===nests.length&&state.defeated>=18){state.bossStarted=true;objective("Defeat the Pine Beetle Queen","Shoot with Rainbow Ricochet, Heartfield Burst, or Long-Range Cookie Toss. Jumping on enemies does not damage them.");floater("THE PINE BEETLE QUEEN",8800,180,"warning");setShake(14)}else if(p.x>8380){p.x=8330;objective("The Queen's lair is sealed",`Destroy ${nests.length-state.nestsDestroyed} nest${nests.length-state.nestsDestroyed===1?"":"s"} and clear the original beetles.`)}}updateBoss(dt);
updateHeroShots(dt);updatePositiveFields(dt);updateCookieBombs(dt);
state.discoveries.forEach((memory,index)=>{if(!state.mem[index]&&Math.abs(p.x-memory.x)<45)collect(index)});
for(const crystal of state.crystals){if(!crystal.got&&Math.abs((p.x+p.w/2)-crystal.x)<48&&Math.abs((p.y+p.h/2)-crystal.y)<70){crystal.got=true;state.score+=750;addParticles(crystal.x,crystal.y,42,"rainbow",1.2);floater("SECRET CRYSTAL +750",crystal.x,crystal.y-35,"combo");setShake(6);syncHud()}}
for(const drop of state.drops){drop.vy+=.22;drop.x+=drop.vx;drop.y+=drop.vy;const dropGround=ground(drop.x)-18;if(drop.y>dropGround){drop.y=dropGround;drop.vy*=-.35}drop.life-=dt;if(overlap(p,{x:drop.x-15,y:drop.y-15,w:30,h:30})){if(drop.type==="hazard"){hurt(drop.x);drop.life=0}else{if(drop.type==="heart")state.health=Math.min(state.maxHealth,state.health+1);else state.score+=250;floater(drop.type==="heart"?"+1 HEART":"RAINBOW ENERGY +250",drop.x,drop.y-20,"combo");drop.life=0;syncHud()}}}state.drops=state.drops.filter(drop=>drop.life>0);
if(p.x>3400&&state.checkpoint<3300){state.checkpoint=3360;ui.checkpoint.classList.remove("hidden");setTimeout(()=>ui.checkpoint.classList.add("hidden"),1900);save()}if(p.x>6900&&state.checkpoint<6800){state.checkpoint=6820;ui.checkpoint.classList.remove("hidden");setTimeout(()=>ui.checkpoint.classList.add("hidden"),1900);save()}
for(let index=0;index<zoneMilestones.length;index++){const zone=zoneMilestones[index];if(p.x>=zone.x&&state.lastZone<index){state.lastZone=index;objective(zone.t,zone.m);floater(zone.t.toUpperCase(),p.x,p.y-55,"combo")}}
if(p.x>9480&&!state.portal){if(state.bossDefeated)finish();else{p.x=9400;objective("The Alaska portal is sealed","Defeat the Pine Beetle Queen.")}}if(state.portal&&p.x>9680){state.complete=true;save();document.body.classList.add("portalExit");setTimeout(()=>location.href="alaska.html",700)}
state.trail.push({x:p.x,y:p.y});if(state.trail.length>70)state.trail.shift();const rigsbyTarget=state.trail[Math.max(0,state.trail.length-20)]||{x:p.x-100,y:p.y},zoeyTarget=state.trail[Math.max(0,state.trail.length-42)]||{x:p.x-175,y:p.y};state.rigsby.x+=(rigsbyTarget.x-state.rigsby.x)*.12;state.rigsby.y+=(ground(state.rigsby.x)-state.rigsby.h-state.rigsby.y)*.22;state.rigsby.frame+=Math.abs(state.rigsby.x-rigsbyTarget.x)*.03;state.zoey.x+=(zoeyTarget.x-state.zoey.x)*.09;state.zoey.y+=(ground(state.zoey.x)-state.zoey.h-state.zoey.y)*.2;
state.camera+=(Math.max(0,Math.min(WORLD-W,p.x-W*.36+p.face*75))-state.camera)*.085;state.shake=Math.max(0,state.shake-dt*.028);state.flash=Math.max(0,state.flash-dt*.0025);ui.trail.style.width=Math.min(100,p.x/(WORLD-250)*100)+"%";ui.altitude.textContent=p.x<1050?"Emerald Shore":p.x<2600?"Whispering Pines":p.x<4050?"Eagle Creek":p.x<5300?"Fallen Timber":p.x<6850?"Crystal Cave":p.x<8200?"Granite Crown":"Infested Summit";
for(const particle of state.particles){particle.x+=particle.vx;particle.y+=particle.vy;particle.vy+=.13;particle.life--}state.particles=state.particles.filter(particle=>particle.life>0);for(const floating of state.floaters){floating.y-=.55;floating.life--}state.floaters=state.floaters.filter(floating=>floating.life>0)
}
function drawPets(){const facing=state.player.face||1;const target=state.player.x-128*facing,moving=Math.abs(state.rigsby.x-target)>8,flip=target<state.rigsby.x;const dogImage=imgs[`rigsby_${moving?"walk":"idle"}`];if(!window.QuestCore.safeSprite(ctx,dogImage,state.rigsby.x-state.camera-10,state.rigsby.y-28,Math.floor(state.time/(moving?90:150)),128,96,78,58,flip))window.QuestCore.drawBeagle(ctx,state.rigsby.x-state.camera,state.rigsby.y,state.time,"rigsby",flip);window.QuestCore.drawBeagle(ctx,state.zoey.x-state.camera,state.zoey.y,state.time,"zoey",state.zoey.x>state.player.x)}
function drawPlayer(){if(!castReady)return {drawn:"waiting",animation:"idle"};return window.QuestCore.drawDude(ctx,{images:imgs,dudeIndex:state.dude,player:{...state.player,inv:state.inv},time:state.time,cameraX:state.camera,groundY:ground(state.player.x)})}
function drawEmergencyPlayer(){return false}
function drawPineBeetleQueen(){if(!state.bossStarted||!state.boss.alive)return;const b=state.boss,x=b.x-state.camera,y=b.y,phase=b.phase,aura=phase===3?"#b653ff":phase===2?"#ff4fb8":"#ff486f";ctx.save();ctx.translate(x,y);if(b.flash>0&&Math.floor(b.flash/40)%2===0)ctx.globalAlpha=.38;ctx.fillStyle="rgba(0,0,0,.3)";ctx.beginPath();ctx.ellipse(0,b.h+15,125,20,0,0,Math.PI*2);ctx.fill();ctx.shadowColor=aura;ctx.shadowBlur=phase===3?36:22;
if(phase>=2){const flap=Math.sin(state.time*.025)*.14;ctx.fillStyle="rgba(216,244,255,.72)";ctx.strokeStyle="rgba(255,255,255,.82)";ctx.lineWidth=4;for(const side of [-1,1]){ctx.save();ctx.rotate(side*flap);ctx.beginPath();ctx.ellipse(side*82,50,76,30,side*.45,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore()}}
ctx.strokeStyle="#211018";ctx.lineWidth=11;ctx.lineCap="round";for(const side of [-1,1])for(let leg=0;leg<3;leg++){const y0=65+leg*22,reach=105+leg*12;ctx.beginPath();ctx.moveTo(side*45,y0);ctx.lineTo(side*reach,y0+24);ctx.lineTo(side*(reach+32),y0+5);ctx.stroke();ctx.strokeStyle=leg===1?aura:"#211018";ctx.lineWidth=4;ctx.stroke();ctx.strokeStyle="#211018";ctx.lineWidth=11}
const abdomen=ctx.createLinearGradient(-90,20,95,130);abdomen.addColorStop(0,"#2a111a");abdomen.addColorStop(.45,phase===3?"#692c80":"#8d2c43");abdomen.addColorStop(1,"#32131d");ctx.fillStyle=abdomen;ctx.beginPath();ctx.ellipse(15,78,92,70,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=phase===3?"#ba75d2":"#e5707f";ctx.lineWidth=5;for(let segment=-2;segment<=2;segment++){ctx.beginPath();ctx.moveTo(segment*22+8,20);ctx.quadraticCurveTo(segment*18+12,76,segment*22+8,132);ctx.stroke()}
ctx.fillStyle="#32131d";ctx.beginPath();ctx.ellipse(-77,53,44,39,-.1,0,Math.PI*2);ctx.fill();ctx.fillStyle="#211018";ctx.beginPath();ctx.moveTo(-109,61);ctx.lineTo(-137,76);ctx.lineTo(-112,48);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(-100,70);ctx.lineTo(-128,91);ctx.lineTo(-105,56);ctx.closePath();ctx.fill();ctx.strokeStyle="#2a1117";ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(-103,35);ctx.quadraticCurveTo(-145,0,-163,15);ctx.moveTo(-92,20);ctx.quadraticCurveTo(-115,-21,-141,-22);ctx.stroke();ctx.fillStyle="#ff5a79";ctx.shadowColor="#ff5a79";ctx.shadowBlur=20;ctx.beginPath();ctx.arc(-92,44,9,0,Math.PI*2);ctx.arc(-65,44,9,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff4a8";ctx.beginPath();ctx.arc(-92,42,3,0,Math.PI*2);ctx.arc(-65,42,3,0,Math.PI*2);ctx.fill();
ctx.fillStyle="#ffe05f";ctx.shadowColor="#ffe05f";ctx.shadowBlur=18;ctx.beginPath();ctx.moveTo(-45,2);ctx.lineTo(-25,-45);ctx.lineTo(0,-10);ctx.lineTo(23,-55);ctx.lineTo(43,-6);ctx.lineTo(68,-38);ctx.lineTo(78,8);ctx.closePath();ctx.fill();ctx.strokeStyle="#b36a17";ctx.lineWidth=4;ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle="#fff";ctx.font="1000 15px system-ui";ctx.textAlign="center";ctx.strokeStyle="rgba(20,8,20,.85)";ctx.lineWidth=5;ctx.strokeText(`PINE BEETLE QUEEN • PHASE ${phase}`,0,-78);ctx.fillText(`PINE BEETLE QUEEN • PHASE ${phase}`,0,-78);ctx.restore()}
function drawBeetle(b){if(!b.alive)return;const x=b.x-state.camera,y=b.y;ctx.save();ctx.translate(x,y);if(b.flash>0&&Math.floor(b.flash/45)%2===0)ctx.globalAlpha=.35;const armored=b.type==="armored",fly=b.type==="flyer";if(fly){ctx.fillStyle="rgba(230,248,255,.68)";ctx.beginPath();ctx.ellipse(-18,-2,16,9,-.45,0,Math.PI*2);ctx.ellipse(18,-2,16,9,.45,0,Math.PI*2);ctx.fill()}ctx.strokeStyle="#26120e";ctx.lineWidth=4;for(const side of [-1,1])for(let i=-1;i<=1;i++){ctx.beginPath();ctx.moveTo(side*10,8+i*7);ctx.lineTo(side*(24+i*2),i*12+4);ctx.stroke()}ctx.strokeStyle="#3b1b14";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-9,-6);ctx.quadraticCurveTo(-20,-20,-28,-18);ctx.moveTo(9,-6);ctx.quadraticCurveTo(20,-20,28,-18);ctx.stroke();ctx.fillStyle=armored?"#263f4a":"#3f140f";ctx.beginPath();ctx.ellipse(0,10,armored?29:24,armored?18:16,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=armored?"#527283":"#9b3f22";ctx.beginPath();ctx.ellipse(3,9,armored?22:18,armored?14:12,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=armored?"#9fc4cf":"#5f2116";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(2,-3);ctx.lineTo(2,22);ctx.stroke();ctx.fillStyle="#29100d";ctx.beginPath();ctx.arc(-21,7,9,0,Math.PI*2);ctx.fill();ctx.fillStyle="#ffcf5a";ctx.beginPath();ctx.arc(-24,5,2.4,0,Math.PI*2);ctx.fill();ctx.restore()}
function draw(){ctx.clearRect(0,0,W,H);const sx=(Math.random()-.5)*state.shake,sy=(Math.random()-.5)*state.shake;ctx.save();ctx.translate(sx,sy);let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,"#79cfee");g.addColorStop(.55,"#d2f1ee");g.addColorStop(1,"#3b8c73");ctx.fillStyle=g;ctx.fillRect(-10,-10,W+20,H+20);if(state.weather==="clouds"){ctx.fillStyle="rgba(80,105,125,.18)";ctx.fillRect(-10,-10,W+20,H+20)}else if(state.weather==="rain"){ctx.fillStyle="rgba(35,55,80,.30)";ctx.fillRect(-10,-10,W+20,H+20)}else if(state.weather==="storm"){ctx.fillStyle="rgba(18,25,48,.48)";ctx.fillRect(-10,-10,W+20,H+20)}else if(state.weather==="rainbow"){const rg=ctx.createLinearGradient(0,0,W,0);["#ff5b7f","#ffbd59","#fff06a","#6df59d","#65d8ff","#b486ff"].forEach((c,i)=>rg.addColorStop(i/5,c));ctx.globalAlpha=.12;ctx.fillStyle=rg;ctx.fillRect(0,0,W,H);ctx.globalAlpha=1}ctx.fillStyle="#fff3ad";ctx.beginPath();ctx.arc(1070,105,48,0,Math.PI*2);ctx.fill();if(state.weather==="rain"||state.weather==="storm"){ctx.strokeStyle=state.weather==="storm"?"rgba(210,235,255,.55)":"rgba(210,235,255,.35)";ctx.lineWidth=2;for(let i=0;i<65;i++){const rx=(i*97+state.time*.35)%W,ry=(i*53+state.time*.7)%H;ctx.beginPath();ctx.moveTo(rx,ry);ctx.lineTo(rx-8,ry+18);ctx.stroke()}}ctx.fillStyle="rgba(255,255,255,.5)";for(let i=0;i<7;i++){const x=(i*240-state.camera*.07+state.time*.018)%(W+300)-100;ctx.beginPath();ctx.ellipse(x,90+(i%3)*34,78,18,0,0,Math.PI*2);ctx.fill()}ctx.fillStyle="#4b7180";for(let i=0;i<10;i++){const x=i*230-state.camera*.12;ctx.beginPath();ctx.moveTo(x,390);ctx.lineTo(x+120,180+(i%3)*55);ctx.lineTo(x+260,390);ctx.fill()}ctx.fillStyle="#2eaccb";ctx.fillRect(0,365,W,205);for(let i=0;i<14;i++){const y=380+i*12,x=(i*117-state.camera*.28+state.time*.035)%(W+180)-90;ctx.strokeStyle="rgba(235,255,255,.28)";ctx.beginPath();ctx.moveTo(x,y);ctx.quadraticCurveTo(x+45,y-4,x+95,y);ctx.stroke()}ctx.fillStyle="#d4be87";ctx.beginPath();ctx.moveTo(-state.camera,FLOOR);for(let x=0;x<=WORLD;x+=100)ctx.lineTo(x-state.camera,ground(x));ctx.lineTo(WORLD-state.camera,H);ctx.lineTo(-state.camera,H);ctx.fill();
ctx.fillStyle="#3f704b";for(let i=0;i<118;i++){const wx=760+i*72,x=wx-state.camera,y=ground(wx),dead=wx>8100&&i%3===0;ctx.fillStyle=dead?"#75523c":"#3f704b";ctx.beginPath();ctx.moveTo(x,y-145-(i%4)*13);ctx.lineTo(x-40,y);ctx.lineTo(x+40,y);ctx.fill()}
// Waterfall, cave, bridge and overlook landmarks
const fallX=3420-state.camera;ctx.fillStyle="rgba(190,245,255,.72)";ctx.fillRect(fallX,205,72,ground(3420)-205);ctx.fillStyle="rgba(255,255,255,.6)";for(let j=0;j<5;j++)ctx.fillRect(fallX+8+j*13,215,5,ground(3420)-225);
const caveX=6220-state.camera,caveY=ground(6220);ctx.fillStyle="#273a43";ctx.beginPath();ctx.arc(caveX,caveY,130,Math.PI,0);ctx.fill();ctx.fillRect(caveX-130,caveY-10,260,30);ctx.fillStyle="#08151d";ctx.beginPath();ctx.arc(caveX,caveY,82,Math.PI,0);ctx.fill();
for(const plat of platforms){const x=plat.x-state.camera;ctx.fillStyle=plat.kind==="log"||plat.kind==="bridge"?"#7b5135":"#8d9697";ctx.fillRect(x,plat.y,plat.w,plat.h);if(plat.kind==="bridge"){ctx.strokeStyle="#d2aa6e";ctx.lineWidth=4;for(let lx=10;lx<plat.w;lx+=32){ctx.beginPath();ctx.moveTo(x+lx,plat.y);ctx.lineTo(x+lx,plat.y+18);ctx.stroke()}}}
for(const c of state.crystals){if(c.got)continue;const x=c.x-state.camera;ctx.save();ctx.translate(x,c.y);ctx.rotate(state.time*.002);ctx.fillStyle="#79f2ff";ctx.shadowColor="#ff5ac8";ctx.shadowBlur=20;ctx.beginPath();ctx.moveTo(0,-18);ctx.lineTo(13,0);ctx.lineTo(0,20);ctx.lineTo(-13,0);ctx.closePath();ctx.fill();ctx.restore();ctx.shadowBlur=0}
for(const m of state.discoveries){const i=state.discoveries.indexOf(m);if(state.mem[i])continue;const x=m.x-state.camera,y=ground(m.x)-62;ctx.fillStyle="#ffe783";ctx.shadowColor="#ffe783";ctx.shadowBlur=18;ctx.beginPath();ctx.arc(x,y,18+Math.sin(state.time*.006+i)*3,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.font="20px serif";ctx.textAlign="center";ctx.fillText("📸",x,y+7)}for(const n of nests){if(!n.alive)continue;const x=n.x-state.camera,y=n.y;ctx.save();ctx.translate(x,y);ctx.fillStyle="#44251d";ctx.beginPath();ctx.ellipse(0,-42,44,58,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#8e4a2f";for(let i=0;i<7;i++){ctx.beginPath();ctx.arc(Math.sin(i*2.1)*24,-70+(i%4)*18,7,0,Math.PI*2);ctx.fill()}ctx.fillStyle="#ffe56f";ctx.font="900 13px system-ui";ctx.textAlign="center";ctx.fillText(`NEST ${n.hp}/${n.maxHp}`,0,-112);ctx.restore()}for(const b of state.beetles)drawBeetle(b);
drawPineBeetleQueen();window.QuestCore.drawDanielCast(ctx,state.player,state.danielCast,state.camera);window.QuestCore.drawPositiveFields(ctx,state.positiveFields,state.time,state.camera);window.QuestCore.drawHeroShots(ctx,state.heroShots,state.time,state.camera);window.QuestCore.drawCookieBombs(ctx,state.cookieBombs,state.time,state.camera);for(const d of state.drops){const x=d.x-state.camera;ctx.font="26px serif";ctx.textAlign="center";ctx.fillText(d.type==="heart"?"❤️":d.type==="hazard"?"🟣":"🌈",x,d.y+Math.sin(state.time*.01)*4)}for(const q of state.particles){ctx.globalAlpha=Math.max(0,q.life/55);ctx.fillStyle=q.kind==="dust"?"#dcc99d":q.kind==="leaves"?["#5b8f49","#d5a64e","#9b5c38"][Math.floor(q.rot*10)%3]:q.kind==="damage"?"#ff6a77":["#ff5ab7","#ffd95a","#55e0ff","#75ed9b","#a778ff"][Math.floor(q.rot*10)%5];ctx.save();ctx.translate(q.x-state.camera,q.y);ctx.rotate(q.rot);ctx.fillRect(-q.size/2,-q.size/2,q.size,q.size);ctx.restore()}ctx.globalAlpha=1;for(const f of state.floaters){ctx.globalAlpha=Math.max(0,f.life/35);ctx.fillStyle=f.kind==="warning"?"#ffe56f":"#fff";ctx.font="1000 20px system-ui";ctx.textAlign="center";ctx.strokeStyle="rgba(8,20,35,.8)";ctx.lineWidth=5;ctx.strokeText(f.text,f.x-state.camera,f.y);ctx.fillText(f.text,f.x-state.camera,f.y)}ctx.globalAlpha=1;
drawPets();drawPlayer();if(state.portal){const x=9690-state.camera,y=335,p=1+Math.sin(state.time*.008)*.08;ctx.save();ctx.translate(x,y);ctx.scale(p,p);ctx.strokeStyle="#ff58ba";ctx.lineWidth=16;ctx.beginPath();ctx.ellipse(0,0,58,82,0,0,Math.PI*2);ctx.stroke();ctx.strokeStyle="#5de4df";ctx.lineWidth=9;ctx.beginPath();ctx.ellipse(0,0,40,62,0,0,Math.PI*2);ctx.stroke();ctx.restore();ctx.fillStyle="#fff";ctx.font="900 16px system-ui";ctx.textAlign="center";ctx.fillText("ALASKA",x,y-105)}ctx.restore();if(state.flash>0){ctx.fillStyle=`rgba(255,255,255,${state.flash})`;ctx.fillRect(0,0,W,H)}if(!state.started){ctx.fillStyle="rgba(2,15,28,.25)";ctx.fillRect(0,0,W,H)}}
function release(){for(const key in state.keys)state.keys[key]=false}
document.querySelectorAll("[data-action]").forEach(b=>{const a=b.dataset.action;b.addEventListener("pointerdown",e=>{e.preventDefault();if(!state.started||state.paused)return;press(a,true);b.classList.add("isPressed");try{b.setPointerCapture(e.pointerId)}catch(_){}},{passive:false});const up=e=>{e.preventDefault();press(a,false);b.classList.remove("isPressed")};b.addEventListener("pointerup",up,{passive:false});b.addEventListener("pointercancel",up,{passive:false});b.addEventListener("lostpointercapture",up)});
function keyAction(e){const action=window.QuestCore.actionForCode(e.code);return ["left","right","jump","power"].includes(action)?action:""}
addEventListener("keydown",e=>{const a=keyAction(e);if(a){e.preventDefault();if(!e.repeat||a==="left"||a==="right")press(a,true)}});addEventListener("keyup",e=>{const a=keyAction(e);if(a){e.preventDefault();press(a,false)}});addEventListener("blur",release);
ui.begin.disabled=true;ui.begin.textContent="Loading Adventure 1 cast…";
window.QuestCore.preloadCastImages(imgs,15000).then(report=>{
castLoadReport=report;
const rendererReport=report.ready?window.QuestCore.verifyCastRenderer(imgs):{ready:false,results:[],failed:[]};
castReady=report.ready&&rendererReport.ready;
window.__TAHOE_CAST_LOAD__=report;
window.__TAHOE_CAST_RENDER_TEST__=rendererReport;
if(castReady){ui.begin.disabled=false;ui.begin.textContent="Play Tahoe";objective("Enter Tahoe","The exact Adventure 1 cast passed all 18 live render tests.");}
else if(!report.ready){ui.begin.disabled=true;ui.begin.textContent="Cast assets missing";objective("Adventure 1 cast could not load",`Missing: ${report.missing.map(item=>item.key).join(", ")}. Upload every file in the 2.5.3 patch.`);console.error("Locked cast preload failed",report);}
else{ui.begin.disabled=true;ui.begin.textContent="Cast renderer blocked";objective("Adventure 1 cast renderer failed",`Failed live render checks: ${rendererReport.failed.map(item=>`${item.dude} ${item.animation}`).join(", ")}.`);console.error("Locked cast renderer self-test failed",rendererReport);}
});
ui.begin.addEventListener("click",()=>reset(false));ui.switch.addEventListener("click",()=>setDude(state.dude+1));ui.pauseBtn.addEventListener("click",()=>{if(!state.started)return;state.paused=!state.paused;ui.pause.classList.toggle("hidden",!state.paused);if(state.paused)release()});ui.resume.addEventListener("click",()=>{state.paused=false;ui.pause.classList.add("hidden")});ui.restart.addEventListener("click",()=>reset(true));ui.replay.addEventListener("click",()=>reset(true));ui.continuePortal.addEventListener("click",()=>{state.portal=true;state.player.x=8840;state.player.y=ground(8840)-state.player.h;ui.trailhead.classList.add("hidden")});
let last=performance.now(),recoveryNoticeShown=false;function loop(now){const dt=Math.min(32,now-last);last=now;try{update(dt);draw()}catch(err){window.__TAHOE_LAST_ERROR__={message:String(err?.message||err),stack:String(err?.stack||""),time:new Date().toISOString()};console.error("Tahoe 2.5.3 display recovery:",err);if(!recoveryNoticeShown){recoveryNoticeShown=true;objective("Tahoe display error","The game refused to draw a fake replacement character. Refresh after the 2.5.3 files finish deploying.")}}requestAnimationFrame(loop)}requestAnimationFrame(loop);
window.__TAHOE_DEBUG__=Object.freeze({get state(){return state},get cast(){return dudes},firePower,setDude});
window.__TAHOE_RELEASE__={version:RELEASE,name:"Adventure 1 Exact Cast Runtime Lock",coreVersion:window.QuestCore.VERSION,castLocked:window.QuestCore.validateCast(dudes),features:["exact Adventure 1 sprite asset preload","no fake character fallback","Adventure 1 animation timing","one locked cast across every adventure","Adventure 1 movement stats","Adventure 1 sprite sheets","Adventure 1 controls","Space fires power","Rainbow Ricochet parity","Heartfield Burst parity","Cookie Toss parity","Rigsby parity","Zoey parity","shoot-only combat","Pine Beetle Queen quality pass"]};
})();
